import json
from pathlib import Path
p=Path(__file__).parent/'content/topics.json'
d=json.load(open(p,encoding='utf-8'))
T={
'functional-testing':{
'en':[
['What is Functional Testing?','Functional Testing verifies whether a system feature behaves according to requirements, business rules, acceptance criteria and user needs. The focus is observable behavior: QA provides inputs, performs actions and compares the actual result with the expected result. It answers the question: “is the system doing what it is supposed to do?”. A login, for example, should not be validated only with correct credentials; we also need to observe invalid passwords, empty fields, incorrect formats, blocked accounts, messages, redirects and session persistence.'],
['Black-box: behavior matters','Functional testing is often associated with Black Box Testing. Knowing the internal implementation is not mandatory to validate behavior: Input → System → Output. This does not mean code, APIs, databases and architecture are irrelevant; that knowledge helps investigate defects. In functional testing, however, the main objective remains verifying the behavior delivered by the product.'],
['What do we want to validate?','Validate flows, business rules, mandatory fields, calculations, messages, permissions, navigation, persistence, integrations perceived by the user and different data combinations. Cover the happy path, alternative, negative and boundary scenarios, prioritizing what represents the greatest risk.'],
['How to think like QA','Turn requirements into questions. In a login: what if the password is wrong? The email does not exist? Fields are empty? There are spaces before the email? The account is blocked? The user double-clicks Sign in? The session has expired? A core QA skill is moving from “I will test the button” to “I will test the behavior of the feature”.'],
['Practical example — Shopping cart','Requirement: “the user can add products to the cart and change the quantity before completing the purchase”. Start by adding one product and validating name, quantity, price and subtotal. Then explore: add the same item again, change 1 to 3, zero or negative quantity, quantity above stock, remove the product, refresh the page and return later.'],
['A simple technique to get started','Ask five questions: 1) What should work? 2) What should not be allowed? 3) What are the boundaries? 4) What happens if I interrupt the flow? 5) What happens next? For a field with a maximum of 100 characters, for example, try 99, 100 and 101.'],
['Turning a scenario into a Test Case','CT001 — Log in with valid credentials\nPrecondition: registered and active user.\nTest data: registered email and valid password.\nSteps: 1) Access the login page. 2) Enter the email. 3) Enter the password. 4) Click Sign in. 5) Verify the page displayed.\nExpected result: the user is authenticated and correctly redirected to the authenticated area.\nDerived cases: CT002 — incorrect password; CT003 — nonexistent user; CT004 — empty fields; CT005 — invalid email; CT006 — blocked account.'],
['When we find different behavior','If the expected behavior is to remain on the login page and display “invalid credentials”, but the system opens a blank page, we have Expected Result ≠ Actual Result. Investigate and, once the defect is confirmed, report a BUG with title, environment, precondition, steps, data, actual result, expected result and evidence.'],
['Tools that can help','Jira, Xray and TestRail help with management; Postman supports API validation; DevTools helps with network and console analysis; SQL can validate persistence; Playwright, Selenium or Cypress can automate stable scenarios. Tools help execute tests, but they do not replace QA reasoning.'],
['Quick checklist','Before finishing: main flow; alternative scenarios; invalid data; mandatory fields; boundaries; error and success messages; business rules; state after the action; interruptions; permissions; persistence; situations not explicitly described in the requirement.'],
['QA Mindset','Do not test only what the system should do. Also test what the user may try to do. Good functional testing is not a long sequence of steps: it is an investigation guided by good questions about product behavior.']],
'es':[
['¿Qué es la Prueba Funcional?','La Prueba Funcional verifica si una funcionalidad del sistema se comporta de acuerdo con los requisitos, reglas de negocio, criterios de aceptación y necesidades del usuario. El foco está en el comportamiento observable: QA proporciona entradas, ejecuta acciones y compara el resultado obtenido con el resultado esperado. Responde a la pregunta: “¿el sistema está haciendo lo que debería hacer?”. Un inicio de sesión, por ejemplo, no debe validarse solo con credenciales correctas; también debemos observar contraseña inválida, campos vacíos, formatos incorrectos, cuenta bloqueada, mensajes, redirecciones y persistencia de la sesión.'],
['Caja negra: el comportamiento importa','Las pruebas funcionales se asocian frecuentemente con Black Box Testing. No es obligatorio conocer la implementación interna para validar el comportamiento: Entrada → Sistema → Salida. Esto no significa que código, API, base de datos y arquitectura sean irrelevantes; ese conocimiento ayuda a investigar defectos. Sin embargo, en la prueba funcional el objetivo principal sigue siendo verificar el comportamiento que entrega el producto.'],
['¿Qué queremos validar?','Valide flujos, reglas de negocio, campos obligatorios, cálculos, mensajes, permisos, navegación, persistencia, integraciones percibidas por el usuario y diferentes combinaciones de datos. Cubra el happy path, escenarios alternativos, negativos y de límite, priorizando lo que represente mayor riesgo.'],
['Cómo pensar como QA','Transforme los requisitos en preguntas. En un login: ¿qué pasa si la contraseña es incorrecta? ¿El correo no existe? ¿Los campos están vacíos? ¿Hay espacios antes del correo? ¿La cuenta está bloqueada? ¿Doble clic en Iniciar sesión? ¿Sesión expirada? Una habilidad central de QA es pasar de “voy a probar el botón” a “voy a probar el comportamiento de la funcionalidad”.'],
['Ejemplo práctico — Carrito de compras','Requisito: “el usuario puede agregar productos al carrito y cambiar la cantidad antes de finalizar la compra”. Comience agregando un producto y validando nombre, cantidad, precio y subtotal. Después explore: agregar nuevamente el mismo artículo, cambiar de 1 a 3, cantidad cero o negativa, cantidad superior al stock, eliminar producto, actualizar la página y regresar posteriormente.'],
['Una técnica sencilla para comenzar','Haga cinco preguntas: 1) ¿Qué debería funcionar? 2) ¿Qué no debería permitirse? 3) ¿Cuáles son los límites? 4) ¿Qué ocurre si interrumpo el flujo? 5) ¿Qué ocurre después? Para un campo con un máximo de 100 caracteres, por ejemplo, pruebe 99, 100 y 101.'],
['Transformando un escenario en Caso de Prueba','CT001 — Iniciar sesión con credenciales válidas\nPrecondición: usuario registrado y activo.\nDatos de prueba: correo registrado y contraseña válida.\nPasos: 1) Acceder a la página de login. 2) Ingresar el correo. 3) Ingresar la contraseña. 4) Hacer clic en Iniciar sesión. 5) Verificar la página presentada.\nResultado esperado: el usuario es autenticado y redirigido correctamente al área autenticada.\nCasos derivados: CT002 — contraseña incorrecta; CT003 — usuario inexistente; CT004 — campos vacíos; CT005 — correo inválido; CT006 — cuenta bloqueada.'],
['Cuando encontramos un comportamiento diferente','Si lo esperado es permanecer en el login y mostrar “credenciales inválidas”, pero el sistema abre una página en blanco, tenemos Expected Result ≠ Actual Result. Investigue y, una vez confirmado el defecto, registre un BUG con título, ambiente, precondición, pasos, datos, resultado actual, resultado esperado y evidencias.'],
['Herramientas que pueden ayudar','Jira, Xray y TestRail ayudan en la gestión; Postman apoya validaciones de API; DevTools ayuda con red y consola; SQL puede validar persistencia; Playwright, Selenium o Cypress pueden automatizar escenarios estables. Las herramientas ayudan a ejecutar pruebas, pero no sustituyen el razonamiento de QA.'],
['Checklist rápido','Antes de finalizar: flujo principal; escenarios alternativos; datos inválidos; obligatoriedad; límites; mensajes de error y éxito; reglas de negocio; estado después de la acción; interrupciones; permisos; persistencia; situaciones no explicitadas en el requisito.'],
['QA Mindset','No pruebe solamente lo que el sistema debería hacer. Pruebe también lo que el usuario puede intentar hacer. Una buena prueba funcional no es una secuencia extensa de pasos: es una investigación guiada por buenas preguntas sobre el comportamiento del producto.']]},
'regression-testing':{
'en':[
['What is Regression Testing?','Regression Testing verifies whether a change introduced side effects in behaviors that already worked. A fix, new feature, refactoring, configuration change or integration can affect seemingly distant areas. Regression protects existing capabilities while the product evolves.'],
['When to execute','After fixes, features, refactoring, dependency changes, configuration, database, APIs, infrastructure or relevant releases. The intensity should follow the risk of the change.'],
['Retest vs Regression','Retest specifically confirms that the corrected defect no longer occurs. Regression verifies whether the fix or another change affected other parts. After a coupon BUG, for example, retest the corrected coupon and perform regression on price, subtotal, promotions, cart and checkout according to impact.'],
['How to choose the scope','Start from the functional and technical diff: what changed, dependencies, shared components, integrations, defect history, criticality, revenue, security and usage. Build an impact zone instead of automatically running the entire suite.'],
['Practical example','Change: new shipping calculation. Possible regression: valid/invalid postal code, shipping methods, free shipping, subtotal, related coupons, cart update, checkout, orders and logistics integration. The scope comes from dependencies and risks.'],
['Full vs selective','Full regression runs a broad suite and costs more time. Selective regression chooses tests based on impact and risk. Not every change requires the entire suite; not every small change is low risk.'],
['Automation','Stable, repetitive, critical and frequently executed scenarios are good candidates. Monitor false positives, execution time and maintenance. Automation without strategy can create a large suite that nobody trusts.'],
['Prioritization','A useful order: critical business flows → directly changed areas → dependencies → integrations → defect history → lower-risk scenarios. Adjust according to time and context.'],
['Quick checklist','Did I understand the change? Map the impact? Retest fixes? Cover critical flows? Integrations? Data? Permissions? Relevant Mobile/Web? Reliable automated tests? Document uncovered risks?'],
['QA Mindset','Regression does not mean “run everything”. It means building confidence that the change did not degrade important existing behaviors.']],
'es':[
['¿Qué es la Prueba de Regresión?','La Prueba de Regresión verifica si un cambio introdujo efectos colaterales en comportamientos que ya funcionaban. Una corrección, nueva funcionalidad, refactorización, cambio de configuración o integración puede afectar áreas aparentemente distantes. La regresión protege capacidades existentes mientras el producto evoluciona.'],
['Cuándo ejecutar','Después de correcciones, funcionalidades, refactorizaciones, cambios de dependencias, configuración, base de datos, APIs, infraestructura o releases relevantes. La intensidad debe acompañar el riesgo del cambio.'],
['Retest vs Regression','Retest confirma específicamente que el defecto corregido dejó de ocurrir. Regression verifica si la corrección u otro cambio afectó otras partes. Después de un BUG en el cupón, por ejemplo, vuelva a probar el cupón corregido y haga regresión en precio, subtotal, promociones, carrito y checkout según el impacto.'],
['Cómo elegir el alcance','Comience por el diff funcional y técnico: qué cambió, dependencias, componentes compartidos, integraciones, historial de defectos, criticidad, ingresos, seguridad y uso. Cree una zona de impacto en lugar de ejecutar toda la suite automáticamente.'],
['Ejemplo práctico','Cambio: nuevo cálculo de envío. Posible regresión: código postal válido/inválido, modalidades, envío gratuito, subtotal, cupones relacionados, actualización del carrito, checkout, pedidos e integración logística. El alcance nace de las dependencias y riesgos.'],
['Completa vs selectiva','La regresión completa ejecuta una suite amplia y requiere más tiempo. La regresión selectiva elige pruebas según impacto y riesgo. No todo cambio exige la suite completa; no todo cambio pequeño es de bajo riesgo.'],
['Automatización','Escenarios estables, repetitivos, críticos y ejecutados con frecuencia son buenos candidatos. Monitoree falsos positivos, tiempo de ejecución y mantenimiento. Automatización sin estrategia puede crear una suite grande en la que nadie confía.'],
['Priorización','Un orden útil: flujos críticos del negocio → áreas directamente modificadas → dependencias → integraciones → historial de defectos → escenarios de menor riesgo. Ajuste según tiempo y contexto.'],
['Checklist rápido','¿Entendí el cambio? ¿Mapeé el impacto? ¿Volví a probar las correcciones? ¿Cubrí flujos críticos? ¿Integraciones? ¿Datos? ¿Permisos? ¿Mobile/Web relevantes? ¿Automatizados confiables? ¿Riesgos no cubiertos documentados?'],
['QA Mindset','Regresión no significa “ejecutar todo”. Significa construir confianza de que el cambio no deterioró comportamientos importantes existentes.']]},
'smoke-testing':{
'en':[
['What is Smoke Testing?','Smoke Testing is a short and objective verification of the most critical paths of a build or environment. Its purpose is not to test everything in depth, but to answer quickly: “is this version stable enough for us to continue testing?”. If essential functions fail, running extensive regression can waste time and produce results with little value.'],
['When to execute','Execute after a deployment, new build, important environment update or before larger cycles such as regression and UAT. In pipelines, an automated smoke suite can also work as an initial gate before more expensive suites.'],
['How to define the scope','Choose a few high-value, high-impact scenarios. In e-commerce: accessible Home, search, PDP, add to cart, authentication and start of checkout. In a banking system: login, balance inquiry and a critical transaction. The scope should reflect the business, not a generic list.'],
['How to execute in practice','Prepare the environment and minimum data, execute critical paths quickly and record only the evidence needed to make a decision. The objective is to detect blockers, unavailability, configuration errors, broken essential integrations and failures that prevent subsequent testing.'],
['Practical example','After an e-commerce deployment: 1) open Home; 2) search for a product; 3) open PDP; 4) add to cart; 5) start checkout. If the cart returns error 500, smoke fails and the team evaluates blocking regression until the problem is understood.'],
['Smoke is not regression','Smoke verifies minimum stability with a few critical scenarios. Regression looks for side effects across much broader coverage. An approved smoke does not mean the product is defect-free; it only means there is minimum confidence to continue.'],
['Approval criteria','Define beforehand which failures block the cycle. A cosmetic failure may not prevent continuation; unavailable login in a product that requires authentication probably does. The decision should consider risk and impact.'],
['Automation','Smoke is an excellent candidate for automation when flows are stable and repetitive. Keep the suite short, reliable and fast; a smoke suite that takes hours loses part of its purpose.'],
['Quick checklist','Correct build; available environment; authentication; main navigation; critical transaction; indispensable integration; minimum data; blocking errors; evidence of the decision to proceed or stop.'],
['QA Mindset','Smoke does not try to prove that everything works. It quickly looks for evidence that it is worth investing in the remaining tests.']],
'es':[
['¿Qué es Smoke Testing?','Smoke Testing es una verificación corta y objetiva de los caminos más críticos de una build o ambiente. Su propósito no es probar todo en profundidad, sino responder rápidamente: “¿esta versión es lo suficientemente estable para continuar probando?”. Si fallan funciones esenciales, ejecutar una regresión extensa puede desperdiciar tiempo y generar resultados poco útiles.'],
['Cuándo ejecutar','Ejecute después de un deploy, nueva build, actualización importante del ambiente o antes de ciclos mayores como regresión y UAT. En pipelines, un smoke automatizado también puede funcionar como gate inicial antes de suites más costosas.'],
['Cómo definir el alcance','Elija pocos escenarios de alto valor y alto impacto. En e-commerce: Home accesible, búsqueda, PDP, agregar al carrito, autenticación e inicio del checkout. En un sistema bancario: login, consulta de saldo y una transacción crítica. El alcance debe reflejar el negocio, no una lista genérica.'],
['Cómo ejecutar en la práctica','Prepare el ambiente y los datos mínimos, ejecute rápidamente los caminos críticos y registre solo las evidencias necesarias para decidir. El objetivo es detectar bloqueos, indisponibilidad, errores de configuración, integraciones esenciales rotas y fallas que impidan pruebas posteriores.'],
['Ejemplo práctico','Después de un deploy de e-commerce: 1) abrir Home; 2) buscar producto; 3) abrir PDP; 4) agregar al carrito; 5) iniciar checkout. Si el carrito devuelve error 500, el smoke falla y el equipo evalúa bloquear la regresión hasta comprender el problema.'],
['Smoke no es regresión','Smoke verifica estabilidad mínima con pocos escenarios críticos. Regresión busca efectos colaterales con una cobertura mucho mayor. Un smoke aprobado no significa que el producto esté libre de defectos; significa solamente que existe confianza mínima para continuar.'],
['Criterios de aprobación','Defina previamente qué fallas bloquean el ciclo. Una falla cosmética puede no impedir continuar; un login indisponible en un producto que exige autenticación probablemente sí. La decisión debe considerar riesgo e impacto.'],
['Automatización','Smoke es un excelente candidato a automatización cuando los flujos son estables y repetitivos. Mantenga la suite corta, confiable y rápida; un smoke que tarda horas pierde parte de su propósito.'],
['Checklist rápido','Build correcta; ambiente disponible; autenticación; navegación principal; transacción crítica; integración indispensable; datos mínimos; errores bloqueantes; evidencia de la decisión de continuar o detenerse.'],
['QA Mindset','Smoke no intenta demostrar que todo funciona. Busca rápidamente evidencias de que vale la pena invertir en el resto de las pruebas.']]},
'sanity-testing':{
'en':[
['What is Sanity Testing?','Sanity Testing is a focused verification of a specific change and its immediate dependencies to quickly decide whether the change makes sense and is stable enough for deeper testing. It is narrower than a general smoke test and usually starts from a known change.'],
['Sanity vs Smoke','Smoke asks whether the build, in general, has minimum stability. Sanity asks whether a changed area looks coherent after a fix or small evolution. The terms vary between companies; what matters is aligning objective and scope.'],
['When to use','After a fix, localized adjustment or small change when we need quick feedback before starting broader regression.'],
['Practical example','Change: shipping calculation. Sanity: calculate shipping for a valid postal code, verify the main method, update quantity and confirm the effect on the total. If the basic calculation fails, it does not make sense to immediately move to dozens of combinations.'],
['How to execute','Identify exactly what changed, select the main path and nearby dependencies, use representative data and look for obvious errors. If it passes, move to detailed tests; if it fails, investigate before expanding.'],
['Appropriate depth','Sanity should not become full regression. It needs to be small enough to provide quick feedback, but deep enough to detect whether the central change is inconsistent.'],
['Quick checklist','Change understood; main path; nearby dependencies; valid data; central rule; persisted result; obvious error; decision to proceed or block.'],
['QA Mindset','Sanity is a focused question: “is this change healthy enough for me to invest in broader testing?”.']],
'es':[
['¿Qué es Sanity Testing?','Sanity Testing es una verificación enfocada en un cambio específico y sus dependencias inmediatas para decidir rápidamente si la modificación tiene sentido y es lo suficientemente estable para pruebas más profundas. Es más limitado que un smoke general y normalmente nace de un cambio conocido.'],
['Sanity vs Smoke','Smoke pregunta si la build, de forma general, posee estabilidad mínima. Sanity pregunta si un área modificada parece coherente después de una corrección o pequeña evolución. Los términos varían entre empresas; lo importante es alinear objetivo y alcance.'],
['Cuándo usar','Después de una corrección, ajuste localizado o pequeño cambio cuando necesitamos feedback rápido antes de iniciar una regresión mayor.'],
['Ejemplo práctico','Cambio: cálculo de envío. Sanity: calcular envío para un código postal válido, verificar la modalidad principal, actualizar cantidad y confirmar el reflejo en el total. Si el cálculo básico falla, no tiene sentido avanzar inmediatamente a decenas de combinaciones.'],
['Cómo ejecutar','Identifique exactamente qué cambió, seleccione el camino principal y dependencias cercanas, use datos representativos y busque errores evidentes. Si pasa, avance a pruebas detalladas; si falla, investigue antes de ampliar.'],
['Profundidad adecuada','Sanity no debe convertirse en regresión completa. Debe ser suficientemente pequeño para dar feedback rápido, pero suficientemente profundo para detectar si el cambio central es incoherente.'],
['Checklist rápido','Cambio entendido; camino principal; dependencias cercanas; dato válido; regla central; resultado persistido; error evidente; decisión de avanzar o bloquear.'],
['QA Mindset','Sanity es una pregunta enfocada: “¿este cambio está lo suficientemente saludable para invertir en pruebas más amplias?”.']]},
'uat':{
'en':[
['What is UAT?','User Acceptance Testing validates whether the solution meets real business needs and is acceptable for use. The perspective is different from simply looking for technical defects: we want to confirm that processes, rules and results allow the user or business to achieve its objectives.'],
['Who participates','Business users, client representatives, Product Owners or representative users usually execute or approve UAT. QA can prepare environment, test data, scenarios, evidence and support, but UAT should not be treated simply as another QA testing round.'],
['Test basis','Use acceptance criteria, business processes, real journeys, critical rules and representative data. The focus should be “does this meet the business need?” and not only “does the screen work?”.'],
['How to prepare','Define scope, participants, environment, access, test data, schedule, entry/exit criteria, severity, defect handling and approval format. Poor preparation creates false blockers.'],
['Practical example','In e-commerce, a business representative can validate a complete purchase: find a product, apply a commercial condition, choose delivery, pay, receive confirmation and verify correct order creation. The flow represents a real operation.'],
['QA role','QA facilitates, clarifies scenarios, collects evidence, helps reproduce problems and separates defects from business questions or incorrect test data. The acceptance decision belongs to the business stakeholders.'],
['Defects and accepted risks','Not every problem needs to prevent acceptance. The business may accept a known risk with a remediation plan. This decision should be explicit and recorded.'],
['Quick checklist','Scope; participants; environment; access; data; journeys; acceptance criteria; defects; risks; evidence; formal approval.'],
['QA Mindset','UAT does not ask only “does it work?”. It asks “does this solution solve the business problem in an acceptable way for the people who will use it?”.']],
'es':[
['¿Qué es UAT?','User Acceptance Testing valida si la solución atiende las necesidades reales del negocio y es aceptable para su uso. La perspectiva es diferente de simplemente buscar defectos técnicos: queremos confirmar que procesos, reglas y resultados permitan que el usuario o negocio alcance sus objetivos.'],
['Quién participa','Usuarios de negocio, representantes del cliente, Product Owners o usuarios representativos normalmente ejecutan o aprueban UAT. QA puede preparar ambiente, datos de prueba, escenarios, evidencias y soporte, pero UAT no debe tratarse simplemente como otra ronda de pruebas de QA.'],
['Base de las pruebas','Use criterios de aceptación, procesos de negocio, jornadas reales, reglas críticas y datos representativos. El foco debe ser “¿esto atiende al negocio?” y no solamente “¿la pantalla funciona?”.'],
['Cómo preparar','Defina alcance, participantes, ambiente, accesos, datos de prueba, cronograma, criterios de entrada/salida, severidad, tratamiento de defectos y formato de aprobación. Una preparación deficiente crea falsos bloqueos.'],
['Ejemplo práctico','En e-commerce, un representante de negocio puede validar una compra completa: encontrar producto, aplicar condición comercial, elegir entrega, pagar, recibir confirmación y verificar la creación correcta del pedido. El flujo representa una operación real.'],
['Papel de QA','QA facilita, aclara escenarios, recopila evidencias, ayuda a reproducir problemas y separa defecto de duda de negocio o datos incorrectos. La decisión de aceptación pertenece a los responsables del negocio.'],
['Defectos y riesgos aceptados','No todo problema necesita impedir la aceptación. El negocio puede aceptar un riesgo conocido con un plan de corrección. Esa decisión debe ser explícita y registrada.'],
['Checklist rápido','Alcance; participantes; ambiente; accesos; datos; jornadas; criterios de aceptación; defectos; riesgos; evidencias; aprobación formal.'],
['QA Mindset','UAT no pregunta solamente “¿funciona?”. Pregunta “¿esta solución resuelve el problema del negocio de manera aceptable para quienes van a utilizarla?”.']]},
'exploratory-testing':{
'en':[
['What is Exploratory Testing?','Exploratory Testing integrates learning, design and execution. Instead of following only previously written cases, QA observes the product, formulates hypotheses, adapts next steps and investigates risks as new information is discovered. Exploring does not mean testing without a method.'],
['When it is valuable','It is especially useful for new features, incomplete requirements, high-risk areas, defect investigations, limited time or when we want to find problems that repeated scripts may not reveal.'],
['Charters','A charter defines a mission without turning the session into a rigid script. Example: “Explore the cart focusing on quantity changes, persistence and price calculation using interruptions and extreme data”.'],
['Heuristics','Use heuristics to vary data, states, sequence, users, permissions, platforms, network, interruptions, time and error conditions. Heuristics help generate questions; they are not mandatory checklists.'],
['Practical example','When exploring image upload: supported/unsupported types, empty file, very large file, long name, special characters, interrupted network, repeated upload, going back during processing and refreshing the page.'],
['Sessions and timebox','A 45–90 minute session with a clear objective helps balance freedom and focus. At the end, debrief: what was tested, discovered, not covered and which questions emerged.'],
['Evidence','Record notes, data, paths, screenshots, videos, logs, defects and ideas. Professional exploration needs to produce communicable learning, even without a detailed test case for every action.'],
['Exploratory vs ad hoc','Ad hoc can be completely improvised. Exploratory Testing is intentional, mission- and learning-oriented. It can use charters, heuristics, mind maps and Session-Based Test Management.'],
['Quick checklist','Mission; risk; timebox; data; heuristics; notes; evidence; defects; questions; uncovered areas; debriefing.'],
['QA Mindset','The value of exploratory testing is learning quickly and using that learning to decide the next test, not clicking randomly.']],
'es':[
['¿Qué es la Prueba Exploratoria?','La Prueba Exploratoria integra aprendizaje, diseño y ejecución. En lugar de seguir solamente casos previamente escritos, QA observa el producto, formula hipótesis, adapta los siguientes pasos e investiga riesgos a medida que descubre nueva información. Explorar no significa probar sin método.'],
['Cuándo es valiosa','Es especialmente útil en funcionalidades nuevas, requisitos incompletos, áreas de alto riesgo, investigaciones de defectos, poco tiempo disponible o cuando queremos encontrar problemas que guiones repetidos pueden no revelar.'],
['Charters','Un charter define una misión sin convertir la sesión en un guion rígido. Ejemplo: “Explorar el carrito con foco en cambio de cantidad, persistencia y cálculo de precio usando interrupciones y datos extremos”.'],
['Heurísticas','Use heurísticas para variar datos, estados, secuencia, usuarios, permisos, plataformas, red, interrupciones, tiempo y condiciones de error. Las heurísticas ayudan a generar preguntas; no son checklists obligatorios.'],
['Ejemplo práctico','Al explorar carga de imagen: tipos soportados/no soportados, archivo vacío, muy grande, nombre largo, caracteres especiales, red interrumpida, carga repetida, volver durante el procesamiento y actualizar la página.'],
['Sesiones y timebox','Una sesión de 45–90 minutos con objetivo claro ayuda a equilibrar libertad y foco. Al final, haga debriefing: qué fue probado, descubierto, no cubierto y qué preguntas surgieron.'],
['Evidencias','Registre notas, datos, caminos, screenshots, videos, logs, defectos e ideas. La exploración profesional necesita producir aprendizaje comunicable, incluso sin un caso de prueba detallado para cada acción.'],
['Exploratorio vs ad hoc','Ad hoc puede ser totalmente improvisado. Exploratory Testing es intencional, orientado por misión y aprendizaje. Puede usar charters, heurísticas, mapas mentales y Session-Based Test Management.'],
['Checklist rápido','Misión; riesgo; timebox; datos; heurísticas; notas; evidencias; defectos; preguntas; áreas no cubiertas; debriefing.'],
['QA Mindset','El valor de la prueba exploratoria está en aprender rápido y usar ese aprendizaje para decidir la próxima prueba, no en hacer clic aleatoriamente.']]},
'integration-testing':{
'en':[
['What is Integration Testing?','Integration Testing verifies whether components, services, APIs, databases, queues or different systems exchange information and work together correctly. A module can work in isolation and still fail when it depends on another system.'],
['What to validate','Contracts, payloads, formats, status codes, authentication, authorization, timeouts, retries, idempotency, mappings, transformations, persistence, event ordering and error handling.'],
['Practical example','An e-commerce platform sends an order to the ERP. Validate order creation, mapped fields, values, taxes, address, identifiers, ERP response, status update and behavior when the ERP is unavailable.'],
['Negative scenarios','400/401/403/404/409/500 response, timeout, incomplete payload, unexpected field, duplication, out-of-order message, unavailable dependency and retry. Integrations also need to be tested when something goes wrong.'],
['Mocks, stubs and real environments','Mocks and stubs help isolate behavior and simulate difficult errors; integrated environments reveal real configuration, network and contract problems. Know the limitation of each approach and combine them according to risk.'],
['Observability','Logs, traces, correlation IDs, metrics and queues help locate the failure boundary. Without observability, an integration error can look like a user interface defect.'],
['Data and consistency','Confirm not only the immediate response, but the final state: persisted data, duplicates, consistency between systems and eventual consistency when applicable.'],
['Quick checklist','Contract; authentication; payload; mapping; success; errors; timeout; retry; idempotency; persistence; logs; traceability; final consistency.'],
['QA Mindset','Do not validate only “A called B”. Validate whether the right information arrived, was interpreted correctly and produced the expected effect end to end across boundaries.']],
'es':[
['¿Qué es la Prueba de Integración?','La Prueba de Integración verifica si componentes, servicios, APIs, bases de datos, colas o sistemas diferentes intercambian información y trabajan juntos correctamente. Un módulo puede funcionar de forma aislada y aun así fallar cuando depende de otro sistema.'],
['Qué validar','Contratos, payloads, formatos, status codes, autenticación, autorización, timeouts, retries, idempotencia, mapeos, transformaciones, persistencia, orden de eventos y tratamiento de errores.'],
['Ejemplo práctico','Un e-commerce envía el pedido al ERP. Valide pedido creado, campos mapeados, valores, impuestos, dirección, identificadores, respuesta del ERP, actualización de estado y comportamiento cuando el ERP no está disponible.'],
['Escenarios negativos','Respuesta 400/401/403/404/409/500, timeout, payload incompleto, campo inesperado, duplicidad, mensaje fuera de orden, dependencia no disponible y retry. Las integraciones también deben probarse cuando algo sale mal.'],
['Mocks, stubs y ambientes reales','Mocks y stubs ayudan a aislar comportamiento y simular errores difíciles; ambientes integrados revelan problemas reales de configuración, red y contrato. Conozca la limitación de cada enfoque y combínelos según el riesgo.'],
['Observabilidad','Logs, traces, correlation IDs, métricas y colas ayudan a localizar la frontera de la falla. Sin observabilidad, un error de integración puede parecer un defecto de la interfaz.'],
['Datos y consistencia','Confirme no solo la respuesta inmediata, sino el estado final: datos persistidos, duplicidades, consistencia entre sistemas y eventual consistency cuando aplique.'],
['Checklist rápido','Contrato; autenticación; payload; mapeo; éxito; errores; timeout; retry; idempotencia; persistencia; logs; trazabilidad; consistencia final.'],
['QA Mindset','No valide solamente “A llamó a B”. Valide si la información correcta llegó, fue interpretada correctamente y produjo el efecto esperado de extremo a extremo entre las fronteras.']]},
'e2e-testing':{
'en':[
['What is E2E Testing?','End-to-End Testing validates a business journey from beginning to end, crossing the relevant layers and integrations. The objective is to confirm that the whole works as a complete experience, not only that each component works in isolation.'],
['When to use','Use it for a few critical flows that represent high value or risk: purchase, payment, registration, contracting, transfer, order creation or another essential process.'],
['Practical example — E-commerce','User finds a product → adds it to the cart → enters data → chooses delivery → pays → receives confirmation → order is created → downstream integration receives the data. The test observes the complete journey.'],
['What to validate','Transitions between steps, preserved data, business rules, integrations, final states, notifications and downstream effects. A failure at any boundary can break the journey.'],
['E2E should not test everything','E2E tends to be slower, more expensive and more fragile. Use unit, API, component and integration tests for detailed coverage and keep E2E lean for truly critical journeys.'],
['Data and environment','Complete flows require reliable test data, available services and state cleanup. Plan data creation and removal to avoid tests that depend on one another.'],
['Diagnosis','When an E2E fails, use logs, APIs, traces and evidence by step to discover where the problem occurred. The complete test detects the break, but does not always identify the cause by itself.'],
['Automation','Automate stable, high-value journeys, avoiding dozens of variations at the E2E layer. Prefer to cover detailed combinations in faster layers.'],
['Quick checklist','Critical journey; preconditions; data; integrations; transitions; payment/main effect; final state; notifications; downstream; cleanup; evidence.'],
['QA Mindset','E2E answers: “can the user complete the real objective from beginning to end?”. Use it for business confidence, not as a replacement for all other testing layers.']],
'es':[
['¿Qué es la Prueba E2E?','End-to-End Testing valida una jornada de negocio de inicio a fin, atravesando las capas e integraciones relevantes. El objetivo es confirmar que el conjunto funciona como una experiencia completa, no solamente que cada componente funciona de forma aislada.'],
['Cuándo usar','Úselo para pocos flujos críticos que representen gran valor o riesgo: compra, pago, registro, contratación, transferencia, creación de pedido u otro proceso esencial.'],
['Ejemplo práctico — E-commerce','El usuario encuentra producto → agrega al carrito → informa datos → elige entrega → paga → recibe confirmación → se crea el pedido → la integración downstream recibe los datos. La prueba observa la jornada completa.'],
['Qué validar','Transiciones entre etapas, datos preservados, reglas de negocio, integraciones, estados finales, notificaciones y efectos downstream. Una falla en cualquier frontera puede romper la jornada.'],
['E2E no debe probar todo','E2E tiende a ser más lento, costoso y frágil. Use pruebas unitarias, de API, componente e integración para cobertura detallada y mantenga E2E reducido para jornadas realmente críticas.'],
['Datos y ambiente','Los flujos completos exigen datos de prueba confiables, servicios disponibles y limpieza de estado. Planifique creación y eliminación de datos para evitar pruebas dependientes entre sí.'],
['Diagnóstico','Cuando un E2E falla, use logs, APIs, traces y evidencias por etapa para descubrir dónde ocurrió el problema. La prueba completa detecta la ruptura, pero no siempre identifica por sí sola la causa.'],
['Automatización','Automatice jornadas estables y de alto valor, evitando decenas de variaciones en la capa E2E. Prefiera cubrir combinaciones detalladas en capas más rápidas.'],
['Checklist rápido','Jornada crítica; precondiciones; datos; integraciones; transiciones; pago/efecto principal; estado final; notificaciones; downstream; limpieza; evidencias.'],
['QA Mindset','E2E responde: “¿el usuario puede completar el objetivo real de inicio a fin?”. Úselo para confianza del negocio, no como sustituto de todas las demás capas de prueba.']]}
}
# short techniques translations
short={
'equivalence-partitioning':{
'en':[['Idea','Instead of testing every possible value, group valid and invalid values that should be handled in the same way.'],['Example','For an accepted age from 18 to 65: classes can be <18, 18–65 and >65.'],['Benefit','Reduces combinations while maintaining representativeness, especially when the input domain is large.'],['Cautions','Classes need to reflect real rules; poorly defined partitions can hide important differences.'],['When to use','Use this knowledge when risk, architecture or the development lifecycle stage requires specific validation. Before applying it, confirm the objective, environment, required data and expected evidence.'],['How QA applies it in practice','Start from the behavior or risk that needs validation, prepare data and environment, execute the technique or tool reproducibly and record evidence that allows the team to understand the result.']],
'es':[['Idea','En lugar de probar todos los valores posibles, agrupe valores válidos e inválidos que deberían tratarse de la misma forma.'],['Ejemplo','Para una edad aceptada de 18 a 65: las clases pueden ser <18, 18–65 y >65.'],['Beneficio','Reduce combinaciones manteniendo representatividad, especialmente cuando el dominio de entrada es grande.'],['Cuidados','Las clases deben reflejar reglas reales; particiones mal definidas pueden ocultar diferencias importantes.'],['Cuándo usar','Use este conocimiento cuando el riesgo, la arquitectura o la etapa del ciclo de desarrollo requiera una validación específica. Antes de aplicarlo, confirme objetivo, ambiente, datos necesarios y evidencias esperadas.'],['Cómo lo aplica QA en la práctica','Comience por el comportamiento o riesgo que necesita validarse, prepare datos y ambiente, ejecute la técnica o herramienta de forma reproducible y registre evidencias que permitan explicar el resultado al equipo.']]},
'boundary-value-analysis':{
'en':[['Idea','Test values exactly at the boundary and immediately below/above when applicable.'],['Example','For the range 18–65, consider 17, 18, 19, 64, 65 and 66 according to the rule and risk.'],['Applications','Numeric fields, dates, sizes, quantities, pagination, upload limits and thresholds.'],['Combination','Use with equivalence partitioning and business rules to avoid a mechanical list of numbers.'],['When to use','Use this knowledge when risk, architecture or the development lifecycle stage requires specific validation. Before applying it, confirm the objective, environment, required data and expected evidence.'],['How QA applies it in practice','Start from the behavior or risk that needs validation, prepare data and environment, execute the technique or tool reproducibly and record evidence that allows the team to understand the result.']],
'es':[['Idea','Pruebe valores exactamente en el límite e inmediatamente por debajo/encima cuando aplique.'],['Ejemplo','Para el intervalo 18–65, considere 17, 18, 19, 64, 65 y 66 según la regla y el riesgo.'],['Aplicaciones','Campos numéricos, fechas, tamaños, cantidades, paginación, límites de carga y thresholds.'],['Combinación','Úsela con partición de equivalencia y reglas de negocio para evitar una lista mecánica de números.'],['Cuándo usar','Use este conocimiento cuando el riesgo, la arquitectura o la etapa del ciclo de desarrollo requiera una validación específica. Antes de aplicarlo, confirme objetivo, ambiente, datos necesarios y evidencias esperadas.'],['Cómo lo aplica QA en la práctica','Comience por el comportamiento o riesgo que necesita validarse, prepare datos y ambiente, ejecute la técnica o herramienta de forma reproducible y registre evidencias que permitan explicar el resultado al equipo.']]},
'decision-table':{
'en':[['Structure','List conditions, possible values and actions/results. Each column can represent a relevant rule.'],['Use','Useful for discounts, permissions, eligibility, shipping, payments and rules with multiple factors.'],['Coverage','Identify valid, impossible and redundant combinations; reduce rules when conditions are indifferent.'],['Test cases','Turn relevant table rules into traceable scenarios, maintaining the link to the business rule.'],['When to use','Use this knowledge when risk, architecture or the development lifecycle stage requires specific validation. Before applying it, confirm the objective, environment, required data and expected evidence.'],['How QA applies it in practice','Start from the behavior or risk that needs validation, prepare data and environment, execute the technique or tool reproducibly and record evidence that allows the team to understand the result.']],
'es':[['Estructura','Liste condiciones, valores posibles y acciones/resultados. Cada columna puede representar una regla relevante.'],['Uso','Es útil para descuentos, permisos, elegibilidad, envío, pagos y reglas con múltiples factores.'],['Cobertura','Identifique combinaciones válidas, imposibles y redundantes; reduzca reglas cuando las condiciones sean indiferentes.'],['Casos de prueba','Transforme reglas relevantes de la tabla en escenarios trazables, manteniendo vínculo con la regla de negocio.'],['Cuándo usar','Use este conocimiento cuando el riesgo, la arquitectura o la etapa del ciclo de desarrollo requiera una validación específica. Antes de aplicarlo, confirme objetivo, ambiente, datos necesarios y evidencias esperadas.'],['Cómo lo aplica QA en la práctica','Comience por el comportamiento o riesgo que necesita validarse, prepare datos y ambiente, ejecute la técnica o herramienta de forma reproducible y registre evidencias que permitan explicar el resultado al equipo.']]},
'state-transition':{
'en':[['Model','Identify states, events, valid transitions, invalid transitions and resulting actions.'],['Examples','Order: created → paid → shipped → delivered; account: active → blocked → reactivated; session: authenticated → expired.'],['Coverage','Test valid paths, forbidden events, repetition, incorrect order and final states.'],['History','Defects may depend on the previous sequence; record initial state and events to reproduce correctly.'],['When to use','Use this knowledge when risk, architecture or the development lifecycle stage requires specific validation. Before applying it, confirm the objective, environment, required data and expected evidence.'],['How QA applies it in practice','Start from the behavior or risk that needs validation, prepare data and environment, execute the technique or tool reproducibly and record evidence that allows the team to understand the result.']],
'es':[['Modelo','Identifique estados, eventos, transiciones válidas, transiciones inválidas y acciones resultantes.'],['Ejemplos','Pedido: creado → pagado → enviado → entregado; cuenta: activa → bloqueada → reactivada; sesión: autenticada → expirada.'],['Cobertura','Pruebe caminos válidos, eventos prohibidos, repetición, orden incorrecto y estados finales.'],['Historial','Los defectos pueden depender de la secuencia anterior; registre el estado inicial y los eventos para reproducir correctamente.'],['Cuándo usar','Use este conocimiento cuando el riesgo, la arquitectura o la etapa del ciclo de desarrollo requiera una validación específica. Antes de aplicarlo, confirme objetivo, ambiente, datos necesarios y evidencias esperadas.'],['Cómo lo aplica QA en la práctica','Comience por el comportamiento o riesgo que necesita validarse, prepare datos y ambiente, ejecute la técnica o herramienta de forma reproducible y registre evidencias que permitan explicar el resultado al equipo.']]}}
T.update(short)
for key,langs in T.items():
    for lang,secs in langs.items():
        d[key][lang]['sections']=secs
# functional qa_tip and insights parity
f=d['functional-testing']
f['en']['qa_tip']='Do not test only what the system should do. Also test what the user may try to do. Good functional testing is not a long sequence of steps: it is an investigation guided by good questions about product behavior.'
f['es']['qa_tip']='No pruebe solamente lo que el sistema debería hacer. Pruebe también lo que el usuario puede intentar hacer. Una buena prueba funcional no es una secuencia extensa de pasos: es una investigación guiada por buenas preguntas sobre el comportamiento del producto.'
f['en']['insights']=[{} for _ in f['pt']['sections']]
f['es']['insights']=[{} for _ in f['pt']['sections']]
f['en']['insights'][0]={'why':'Many defects perceived by users are in feature behavior: login, calculations, forms, cart or checkout. Functional testing turns requirements and rules into observable evidence.'}
f['es']['insights'][0]={'why':'Gran parte de los defectos percibidos por el usuario está en el comportamiento de las funcionalidades: login, cálculos, formularios, carrito o checkout. La prueba funcional transforma requisitos y reglas en evidencias observables.'}
f['en']['insights'][1]={'apply':'Start with the happy path and then derive negative, alternative and boundary scenarios. For each one, define input, action and expected result without unnecessarily duplicating cases.'}
f['es']['insights'][1]={'apply':'Comience por el happy path y después derive escenarios negativos, alternativos y de límite. Para cada uno, defina entrada, acción y resultado esperado sin duplicar casos innecesariamente.'}
f['en']['insights'][8]={'good':'Write reproducible steps and objective expected results. Avoid phrases such as “the system should work correctly”; describe exactly what should happen.','caution':'A test case does not need to validate everything at once. Excessively long cases make maintenance, diagnosis and reuse more difficult.'}
f['es']['insights'][8]={'good':'Escriba pasos reproducibles y resultados esperados objetivos. Evite frases como “el sistema debe funcionar correctamente”; describa exactamente qué debe ocurrir.','caution':'Un caso de prueba no necesita validar todo al mismo tiempo. Casos excesivamente largos dificultan mantenimiento, diagnóstico y reutilización.'}
json.dump(d,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=2)
print('updated',len(T),'testing topics')
