import json, os, re
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from reportlab.lib.units import mm
ROOT='/mnt/data/qa_rc2'; D=json.load(open(ROOT+'/content/topics.json',encoding='utf8'))
styles=getSampleStyleSheet(); styles.add(ParagraphStyle(name='Small2',parent=styles['BodyText'],fontSize=9,leading=13,textColor=colors.HexColor('#34536f'))); styles.add(ParagraphStyle(name='Code2',parent=styles['BodyText'],fontName='Courier',fontSize=8.5,leading=12,backColor=colors.HexColor('#f3f8fc'),borderPadding=6));
def safe(s): return re.sub(r'&(?!(amp|lt|gt|quot|apos);)','&amp;',str(s)).replace('<','&lt;').replace('>','&gt;')
def doc(path,title,subtitle,sections,footer='QA Lab Brasil'):
 os.makedirs(os.path.dirname(path),exist_ok=True); story=[Paragraph(safe(title),styles['Title']),Spacer(1,5),Paragraph(safe(subtitle),styles['BodyText']),Spacer(1,12)]
 for h,b in sections:
  story += [Paragraph(safe(h),styles['Heading2']),Spacer(1,4)]
  lines=str(b).split('\n')
  for line in lines:
   if re.match(r'^(CT|TC|CP)\d+',line): story.append(Paragraph('<b>'+safe(line)+'</b>',styles['BodyText']))
   elif ':' in line and len(line.split(':',1)[0])<35:
    a,c=line.split(':',1); story.append(Paragraph('<b>'+safe(a)+':</b> '+safe(c),styles['BodyText']))
   else: story.append(Paragraph(safe(line),styles['BodyText']))
   story.append(Spacer(1,3))
  story.append(Spacer(1,7))
 story += [Spacer(1,12),Paragraph(footer,styles['Small2'])]
 SimpleDocTemplate(path,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=16*mm,bottomMargin=16*mm,title=title).build(story)
langs={'pt':('Guia de Aprendizado','Instalação e Configuração'),'en':('Learning Guide','Installation & Setup'),'es':('Guía de Aprendizaje','Instalación y Configuración')}
for k,v in D.items():
 for lang in ['pt','en','es']:
  if lang not in v: continue
  d=v[lang]; doc(f'{ROOT}/pdf/{lang}/{k}.pdf',d['title'],d.get('subtitle',''),d.get('sections',[]))
# Tailored installation recipes
recipes={
'java':{'pt':['Baixe um JDK compatível no site oficial indicado pelo QA Lab.','Execute o instalador e anote a pasta do JDK, normalmente em C:\\Program Files\\Java\\jdk-XX.','Abra um novo terminal e valide: java -version e javac -version.','Se JAVA_HOME for exigido, crie a variável apontando para a pasta do JDK e adicione %JAVA_HOME%\\bin ao Path.','Se esqueceu o PATH: abra Variáveis de Ambiente > Path > Novo, adicione a pasta bin do JDK, confirme, feche e reabra o terminal.','Se versões divergirem, revise JAVA_HOME e a ordem do Path.'],
'en':['Download a compatible JDK from the official resource linked by QA Lab.','Run the installer and note the JDK folder, commonly C:\\Program Files\\Java\\jdk-XX.','Open a new terminal and validate: java -version and javac -version.','When JAVA_HOME is required, point it to the JDK folder and add %JAVA_HOME%\\bin to Path.','If PATH was missed: open Environment Variables > Path > New, add the JDK bin folder, confirm and reopen the terminal.','If versions differ, review JAVA_HOME and Path order.'],
'es':['Descargue un JDK compatible desde el recurso oficial enlazado por QA Lab.','Ejecute el instalador y anote la carpeta del JDK, normalmente C:\\Program Files\\Java\\jdk-XX.','Abra una terminal nueva y valide: java -version y javac -version.','Cuando se requiera JAVA_HOME, apunte a la carpeta del JDK y agregue %JAVA_HOME%\\bin al Path.','Si olvidó PATH: abra Variables de entorno > Path > Nuevo, agregue la carpeta bin del JDK, confirme y reabra la terminal.','Si las versiones difieren, revise JAVA_HOME y el orden del Path.']},
'python':{'pt':['Use o instalador oficial atual do Python para Windows. Durante a instalação, habilite a opção de disponibilizar Python no PATH quando apresentada.','Abra um novo terminal e valide python --version e py --version; valide também pip --version.','Se Python já foi instalado e python não é reconhecido, teste py. Depois localize a instalação e adicione ao Path a pasta do Python e, quando necessário, a pasta Scripts.','Feche e reabra o terminal após alterar o Path.','Crie um ambiente virtual: python -m venv .venv. Ative-o antes de instalar dependências do projeto.'],
'en':['Use the current official Python installer for Windows. During setup, enable the option that makes Python available on PATH when offered.','Open a new terminal and validate python --version and py --version; also validate pip --version.','If Python is installed but python is not recognized, try py. Then locate the installation and add the Python folder and, when needed, Scripts to Path.','Close and reopen the terminal after changing Path.','Create a virtual environment: python -m venv .venv. Activate it before installing project dependencies.'],
'es':['Use el instalador oficial actual de Python para Windows. Durante la instalación, habilite la opción que agrega Python al PATH cuando se muestre.','Abra una terminal nueva y valide python --version y py --version; valide también pip --version.','Si Python está instalado pero python no se reconoce, pruebe py. Después agregue al Path la carpeta de Python y, cuando sea necesario, Scripts.','Cierre y reabra la terminal después de cambiar el Path.','Cree un entorno virtual: python -m venv .venv. Actívelo antes de instalar dependencias.']},
'playwright':{'pt':['Instale uma versão LTS compatível do Node.js e valide node --version e npm --version.','Crie/abra o projeto e instale Playwright conforme a documentação oficial.','Instale os browsers exigidos pelo projeto com npx playwright install.','Execute um primeiro teste e abra o relatório para confirmar que ambiente, browsers e dependências estão corretos.','Em CI, instale também dependências do sistema quando a imagem exigir.'], 'en':['Install a compatible Node.js LTS and validate node --version and npm --version.','Create/open the project and install Playwright according to the official docs.','Install required browsers with npx playwright install.','Run a first test and open the report to validate environment, browsers and dependencies.','In CI, also install system dependencies when the image requires them.'], 'es':['Instale una versión LTS compatible de Node.js y valide node --version y npm --version.','Cree/abra el proyecto e instale Playwright según la documentación oficial.','Instale los navegadores requeridos con npx playwright install.','Ejecute una primera prueba y abra el reporte para validar ambiente, navegadores y dependencias.','En CI, instale también dependencias del sistema cuando la imagen lo requiera.']},
'appium':{'pt':['Instale Node.js/npm e valide as versões.','Instale o servidor Appium conforme a documentação oficial e valide appium --version.','Para Android, instale Android Studio/SDK, configure as variáveis necessárias e valide adb devices.','Instale o driver UiAutomator2 com appium driver install uiautomator2.','Execute appium driver doctor uiautomator2 quando disponível e corrija os requisitos apontados.','Inicie emulador/dispositivo, suba o servidor Appium e valide uma primeira sessão antes de criar uma suíte maior.'], 'en':['Install Node.js/npm and validate versions.','Install the Appium server according to official docs and validate appium --version.','For Android, install Android Studio/SDK, configure required environment variables and validate adb devices.','Install UiAutomator2 with appium driver install uiautomator2.','Run appium driver doctor uiautomator2 when available and fix reported prerequisites.','Start an emulator/device, start Appium and validate a first session before building a larger suite.'], 'es':['Instale Node.js/npm y valide versiones.','Instale el servidor Appium según la documentación oficial y valide appium --version.','Para Android, instale Android Studio/SDK, configure variables necesarias y valide adb devices.','Instale UiAutomator2 con appium driver install uiautomator2.','Ejecute appium driver doctor uiautomator2 cuando esté disponible y corrija prerrequisitos.','Inicie emulador/dispositivo, servidor Appium y valide una primera sesión antes de crear una suite mayor.']},
'robot-framework':{'pt':['Instale Python e valide python --version e pip --version.','Crie e ative um ambiente virtual para o projeto.','Instale Robot Framework com pip install robotframework.','Valide robot --version.','Crie um arquivo .robot mínimo, execute com robot arquivo.robot e abra log.html/report.html.','Instale bibliotecas adicionais somente conforme a necessidade do projeto.'], 'en':['Install Python and validate python --version and pip --version.','Create and activate a project virtual environment.','Install Robot Framework with pip install robotframework.','Validate robot --version.','Create a minimal .robot file, run robot file.robot and open log.html/report.html.','Install additional libraries only as required by the project.'], 'es':['Instale Python y valide python --version y pip --version.','Cree y active un entorno virtual para el proyecto.','Instale Robot Framework con pip install robotframework.','Valide robot --version.','Cree un archivo .robot mínimo, ejecute robot archivo.robot y abra log.html/report.html.','Instale librerías adicionales solo según la necesidad del proyecto.']}}
installables=['java','python','nodejs','npm','playwright','selenium','cypress','robot-framework','appium','git','vscode','intellij','eclipse','spring-tools','maven','gradle','jenkins','docker','kubernetes','terraform','jmeter','k6','gatling','locust','dbeaver','mysql-workbench','pgadmin','oracle-sql-developer','mongodb-compass','adb','charles-proxy','fiddler','proxyman']
for k in installables:
 if k not in D: continue
 for lang in ['pt','en','es']:
  d=D[k][lang]; meta=D[k].get('_meta',{}); steps=recipes.get(k,{}).get(lang)
  if not steps:
   if lang=='pt': steps=['Confira os pré-requisitos e a versão suportada na documentação oficial.','Use o link oficial de download disponibilizado pelo QA Lab e conclua a instalação padrão.','Se a ferramenta expõe comandos no terminal, valide se o executável está disponível no PATH; se não estiver, localize a pasta do executável e adicione-a manualmente ao Path, então reabra o terminal.','Abra a ferramenta ou execute o comando de versão para confirmar a instalação.','Faça um primeiro uso mínimo antes de adicionar plugins, drivers ou integrações.','Em caso de erro, confirme versão, permissões, dependências e documentação oficial antes de alterar o projeto.']
   elif lang=='en': steps=['Check prerequisites and supported versions in the official documentation.','Use the official download link provided by QA Lab and complete the standard installation.','If the tool exposes terminal commands, validate that its executable is on PATH; otherwise locate its executable folder, add it to Path and reopen the terminal.','Open the tool or run its version command to confirm installation.','Perform a minimal first use before adding plugins, drivers or integrations.','On errors, confirm version, permissions, dependencies and official docs before changing the project.']
   else: steps=['Revise prerrequisitos y versiones soportadas en la documentación oficial.','Use el enlace oficial de descarga de QA Lab y complete la instalación estándar.','Si la herramienta usa comandos de terminal, valide que el ejecutable esté en PATH; si no, localice su carpeta, agréguela al Path y reabra la terminal.','Abra la herramienta o ejecute el comando de versión para confirmar la instalación.','Realice un primer uso mínimo antes de agregar plugins, drivers o integraciones.','Ante errores, confirme versión, permisos, dependencias y documentación oficial antes de cambiar el proyecto.']
  site=meta.get('official') or meta.get('docs') or meta.get('download') or ''
  h=langs[lang][1]; sections=[(h, d.get('subtitle','')),(('Fonte oficial' if lang=='pt' else 'Official source' if lang=='en' else 'Fuente oficial'),site or 'Consulte os recursos oficiais indicados no módulo.'),(('Passo a passo' if lang=='pt' else 'Step by step' if lang=='en' else 'Paso a paso'),'\n'.join(f'{i+1}. {s}' for i,s in enumerate(steps))),(('Troubleshooting' if lang!='es' else 'Solución de problemas'),('Se algo falhar, compare a mensagem de erro com versão, PATH/variáveis, permissões e dependências.' if lang=='pt' else 'If something fails, compare the error with version, PATH/environment variables, permissions and dependencies.' if lang=='en' else 'Si algo falla, compare el error con versión, PATH/variables, permisos y dependencias.'))]
  doc(f'{ROOT}/pdf/{lang}/{k}-installation.pdf',d['title']+' - '+h,d.get('subtitle',''),sections)
