import json,re,os
ROOT='/mnt/data/qa_final'
p=ROOT+'/content/topics.json'
D=json.load(open(p,encoding='utf-8'))

def topic(icon,color,group,official,docs,download, langs):
    return {'_meta':{'icon':icon,'color':color,'group':group,'official':official,'docs':docs,'download':download},**langs}

def L(title,subtitle,sections,tip): return {'title':title,'subtitle':subtitle,'sections':sections,'qa_tip':tip,'insights':[{} for _ in sections]}

# Upgrade existing topics with context-specific, source-aligned content.
D['k6']['pt']=L('k6','Performance e load testing orientados por código, métricas e thresholds.',[
 ['O que é k6','k6 é uma ferramenta da Grafana para testes de carga e performance. Os testes são definidos como código e podem exercitar APIs e aplicações com usuários virtuais, duração, estágios e critérios de aprovação.'],
 ['O que o QA mede','Não observe apenas tempo médio. Avalie percentis de duração, taxa de falhas, throughput, checks e métricas do sistema. O objetivo é relacionar carga, comportamento percebido e capacidade do ambiente.'],
 ['Cenários e carga','Modele a carga de acordo com o uso esperado: smoke de performance, carga média, pico, stress ou soak. Defina usuários virtuais, duração e ramp-up/ramp-down de forma coerente com o objetivo.'],
 ['Thresholds','Thresholds transformam expectativas de performance em critérios verificáveis, por exemplo limitar taxa de falhas ou exigir determinado percentil de resposta. Um teste pode executar tecnicamente e ainda falhar por não cumprir o threshold.'],
 ['Primeiro fluxo prático','Instale k6, valide com k6 version, crie um script com k6 new e execute com k6 run. Comece com um endpoint controlado e aumente carga somente depois de compreender a linha de base.'],
 ['Uso em CI/CD','k6 pode executar em pipelines para detectar regressões de performance. Evite usar o mesmo volume de um teste pesado em todo commit; combine testes rápidos com execuções maiores em momentos apropriados.'],
 ['Ponto de atenção','Não execute carga relevante contra produção ou serviços de terceiros sem autorização e planejamento. Ambiente, dados, cache, limites externos e observabilidade influenciam a interpretação dos resultados.']
],'Performance testing útil começa por objetivo e critérios claros, não por gerar o maior número possível de requisições.')
D['k6']['en']=L('k6','Code-driven performance and load testing with metrics and thresholds.',[
 ['What k6 is','k6 is a Grafana tool for load and performance testing. Tests are defined as code and can exercise APIs and applications with virtual users, duration, stages and pass/fail criteria.'],['What QA measures','Do not rely only on averages. Review duration percentiles, failure rate, throughput, checks and system metrics.'],['Load scenarios','Model smoke, average load, peak, stress or soak scenarios according to the objective.'],['Thresholds','Thresholds turn performance expectations into verifiable criteria such as failure-rate or response-time percentile limits.'],['First practical flow','Install k6, validate with k6 version, create a script with k6 new and execute it with k6 run.'],['CI/CD use','Use fast performance checks in pipelines and schedule heavier tests appropriately.'],['Attention point','Do not generate meaningful load against production or third parties without authorization and planning.']],'Useful performance testing starts with objectives and criteria, not maximum request volume.')
D['k6']['es']=L('k6','Pruebas de performance y carga orientadas por código, métricas y thresholds.',[
 ['Qué es k6','k6 es una herramienta de Grafana para pruebas de carga y performance. Los tests se definen como código y pueden ejercitar APIs y aplicaciones con usuarios virtuales, duración, etapas y criterios.'],['Qué mide QA','No observe solo promedios. Revise percentiles, tasa de fallos, throughput, checks y métricas del sistema.'],['Escenarios de carga','Modele smoke de performance, carga media, pico, stress o soak según el objetivo.'],['Thresholds','Los thresholds convierten expectativas de performance en criterios verificables.'],['Primer flujo práctico','Instale k6, valide con k6 version, cree un script con k6 new y ejecútelo con k6 run.'],['Uso en CI/CD','Combine verificaciones rápidas en pipeline con pruebas más pesadas en momentos adecuados.'],['Punto de atención','No genere carga relevante contra producción o terceros sin autorización y planificación.']],'Una buena prueba de performance comienza con objetivos y criterios claros.')

D['zap']['pt']=L('OWASP ZAP','DAST e análise de segurança de aplicações Web em ambientes autorizados.',[
 ['O que é OWASP ZAP','ZAP é um proxy de segurança open source que permite observar e manipular tráfego HTTP/HTTPS e apoiar testes dinâmicos de aplicações Web.'],['Passive Scan','O Passive Scan analisa mensagens que passam pelo proxy sem enviar ataques adicionais. É uma boa porta de entrada para observar headers, cookies e possíveis problemas enquanto o QA navega pela aplicação.'],['Active Scan','O Active Scan envia requisições de ataque para procurar vulnerabilidades. Use somente em sistemas e ambientes para os quais exista autorização explícita.'],['Quick Start e proxy','O Quick Start pode spider/scanear uma URL e também iniciar navegadores pré-configurados para usar o proxy do ZAP. Em cenários avançados, configure o browser ou testes automatizados para trafegar pelo proxy.'],['QA e DAST no pipeline','ZAP pode participar de pipelines em ambientes controlados. Defina escopo, autenticação, contexto e critérios de triagem; findings automáticos precisam de análise para separar risco real de falso positivo.'],['Ponto de atenção','Nunca execute Active Scan em sistemas sem autorização. Scanners podem alterar estado, criar dados e gerar carga significativa. Preserve evidências e trate credenciais/certificados com cuidado.']
],'Segurança automatizada ajuda a encontrar sinais; a decisão de risco exige contexto e autorização.')
D['zap']['en']=L('OWASP ZAP','DAST and Web application security analysis in authorized environments.',[['What OWASP ZAP is','ZAP is an open-source security proxy for observing and manipulating HTTP/HTTPS traffic and supporting dynamic Web application testing.'],['Passive Scan','Passive Scan analyzes proxied messages without sending additional attacks.'],['Active Scan','Active Scan sends attack requests to look for vulnerabilities and must only be used with explicit authorization.'],['Quick Start and proxy','Quick Start can spider/scan a URL and launch browsers preconfigured to proxy through ZAP.'],['QA and DAST in CI','Use controlled environments, authentication/context configuration and triage criteria for automated findings.'],['Attention point','Never run Active Scan against systems you are not authorized to test.']],'Automated security findings need context, authorization and human triage.')
D['zap']['es']=L('OWASP ZAP','DAST y análisis de seguridad Web en ambientes autorizados.',[['Qué es OWASP ZAP','ZAP es un proxy de seguridad open source para observar/manipular tráfico HTTP/HTTPS y apoyar pruebas dinámicas.'],['Passive Scan','Analiza mensajes que pasan por el proxy sin enviar ataques adicionales.'],['Active Scan','Envía solicitudes de ataque y solo debe utilizarse con autorización explícita.'],['Quick Start y proxy','Quick Start puede explorar/escanear una URL e iniciar navegadores configurados con el proxy.'],['QA y DAST en CI','Defina ambiente, autenticación, contexto y criterios de triage.'],['Punto de atención','Nunca ejecute Active Scan sin autorización.']],'Los hallazgos automáticos de seguridad necesitan contexto y análisis.')

D['pact']['pt']=L('Pact / Contract Testing','Consumer-driven contract testing para reduzir falhas de integração entre serviços.',[
 ['O que é Contract Testing','Contract Testing verifica se consumidor e provedor concordam sobre a interface usada na integração. Ele não substitui testes funcionais ou E2E; reduz o risco de incompatibilidades entre serviços.'],['Como Pact funciona','Em um fluxo consumer-driven, o consumidor descreve as interações que espera do provedor. Essas interações geram um contrato Pact, que depois é verificado contra o provedor.'],['Consumer e Provider','Consumer é quem faz a chamada; Provider é quem atende a chamada. Um contrato descreve requests e responses relevantes sem exigir que todos os sistemas estejam disponíveis ao mesmo tempo durante o teste do consumidor.'],['Pact Broker/PactFlow','Em times distribuídos, contratos podem ser publicados e versionados em um broker para que consumidores e provedores verifiquem compatibilidade ao longo das versões.'],['Onde QA agrega valor','QA ajuda a identificar integrações críticas, cenários de erro, compatibilidade de versões e lacunas que não devem ficar dependentes apenas de E2E tardio.'],['Ponto de atenção','Não transforme Pact em uma cópia completa do payload de produção. Contratos excessivamente rígidos aumentam acoplamento e podem quebrar por mudanças irrelevantes para o consumidor.']
],'Use Contract Testing para obter feedback rápido sobre compatibilidade entre serviços, mantendo E2E para fluxos que realmente exigem integração completa.')
D['pact']['en']=L('Pact / Contract Testing','Consumer-driven contract testing to reduce integration failures between services.',[['What Contract Testing is','Contract testing verifies that a consumer and provider agree on the interface used by an integration. It complements rather than replaces functional or E2E testing.'],['How Pact works','The consumer describes expected interactions and produces a Pact contract that is later verified against the provider.'],['Consumer and Provider','The consumer makes the call; the provider serves it. Contracts allow fast compatibility feedback without requiring the full system for every consumer test.'],['Pact Broker/PactFlow','Teams can publish and version contracts in a broker to coordinate compatibility across releases.'],['QA value','QA can identify critical integrations, error scenarios and version-compatibility risks.'],['Attention point','Avoid over-specifying fields the consumer does not depend on; overly rigid contracts create unnecessary coupling.']],'Use contract testing for fast compatibility feedback and reserve E2E for flows that require full integration.')
D['pact']['es']=L('Pact / Contract Testing','Consumer-driven contract testing para reducir fallos de integración entre servicios.',[['Qué es Contract Testing','Verifica que consumidor y proveedor estén de acuerdo sobre la interfaz de integración. Complementa, no reemplaza, pruebas funcionales o E2E.'],['Cómo funciona Pact','El consumidor describe interacciones esperadas y genera un contrato que luego se verifica contra el proveedor.'],['Consumer y Provider','Consumer realiza la llamada y Provider la atiende.'],['Pact Broker/PactFlow','Los contratos pueden publicarse/versionarse para coordinar compatibilidad entre equipos.'],['Valor para QA','QA puede identificar integraciones críticas, errores y riesgos de compatibilidad.'],['Punto de atención','Evite contratos demasiado rígidos con campos que el consumidor no necesita.']],'Use Contract Testing para feedback rápido de compatibilidad entre servicios.')

D['sonarqube']['pt']=L('SonarQube','Análise automatizada de código e Quality Gates integrada ao fluxo de desenvolvimento.',[
 ['O que é SonarQube','SonarQube Server recebe resultados de análise de código, identifica problemas relacionados a confiabilidade, segurança e manutenibilidade e apresenta métricas para apoiar revisão contínua de código.'],['SonarScanner e análise','O scanner executa no projeto ou CI/CD e envia os resultados ao servidor. A análise não substitui testes funcionais: ela observa propriedades do código que exigem outra camada de evidência.'],['Quality Gate','Quality Gates aplicam condições para decidir se o código atende à política de qualidade. O status pode ser usado no pipeline e em pull requests para impedir avanço quando critérios definidos não são cumpridos.'],['Cobertura de testes','SonarQube normalmente importa cobertura produzida por ferramentas de teste; ele não executa seus testes para criar cobertura por conta própria. Interprete cobertura junto com risco e qualidade dos testes.'],['Como QA participa','QA pode colaborar na definição de critérios, acompanhar tendências de qualidade, entender falhas do gate e relacionar resultados estáticos com riscos observados em testes e produção.'],['Ponto de atenção','Quality Gate não é sinônimo de qualidade total. Passar no gate não comprova regras de negócio, usabilidade, acessibilidade, performance ou integração.']
],'Use análise estática e Quality Gates como uma camada de feedback, não como substituto da estratégia de testes.')
D['sonarqube']['en']=L('SonarQube','Automated code analysis and Quality Gates integrated with development workflows.',[['What SonarQube is','SonarQube Server processes code analysis results and reports reliability, security and maintainability issues and metrics.'],['SonarScanner','The scanner runs on the project or CI host and sends analysis results to the server. Static analysis does not replace functional testing.'],['Quality Gate','Quality Gates apply conditions to decide whether code meets the quality policy and can report/fail status in CI or pull requests.'],['Test coverage','SonarQube generally imports coverage reports produced by test tools; it does not create meaningful coverage by executing your tests itself.'],['QA participation','QA can collaborate on criteria, trends and risk interpretation across static analysis, testing and production evidence.'],['Attention point','Passing a Quality Gate does not prove business behavior, usability, accessibility, performance or integration quality.']],'Treat static analysis and Quality Gates as one feedback layer in a broader quality strategy.')
D['sonarqube']['es']=L('SonarQube','Análisis automatizado de código y Quality Gates integrados al flujo de desarrollo.',[['Qué es SonarQube','SonarQube Server procesa análisis de código e informa problemas/métricas de confiabilidad, seguridad y mantenibilidad.'],['SonarScanner','El scanner ejecuta en el proyecto o CI y envía resultados al servidor.'],['Quality Gate','Los Quality Gates aplican condiciones y pueden bloquear el avance cuando no se cumplen criterios.'],['Cobertura','SonarQube importa reportes de cobertura producidos por herramientas de test; no reemplaza la ejecución de pruebas.'],['Participación de QA','QA puede colaborar en criterios, tendencias y análisis de riesgo.'],['Punto de atención','Aprobar el Quality Gate no demuestra reglas de negocio, usabilidad, accesibilidad, performance o integración.']],'Use análisis estático como una capa de feedback dentro de una estrategia mayor.')

D['prometheus']['pt']=L('Prometheus','Coleta, armazenamento e consulta de métricas em séries temporais para monitoramento e observabilidade.',[
 ['O que é Prometheus','Prometheus coleta métricas de targets, normalmente por scraping de endpoints HTTP, e armazena os valores como séries temporais com timestamps e labels.'],['Scraping e targets','O arquivo de configuração define targets e frequência de coleta. Antes de interpretar gráficos, confirme se o target está UP e se a métrica realmente está sendo exposta/coletada.'],['PromQL','PromQL é a linguagem de consulta usada para selecionar e agregar séries temporais. Comece com consultas simples e só depois avance para taxas, agregações e janelas de tempo.'],['QA e observabilidade','Durante performance, integração ou validações pós-deploy, QA pode correlacionar comportamento funcional com latência, erros, consumo de recursos e outras métricas expostas pelo sistema.'],['Alertas e contexto','Métricas podem alimentar regras e alertas. Um alerta útil precisa representar uma condição acionável; excesso de alertas sem contexto cria ruído.'],['Ponto de atenção','Prometheus não “entende” sozinho a qualidade do produto. Métricas precisam de nomes, labels e objetivos coerentes; cardinalidade excessiva também pode gerar custo e complexidade.']
],'Métricas são evidência operacional: use-as para explicar comportamento, não apenas para decorar dashboards.')
D['prometheus']['en']=L('Prometheus','Time-series metrics collection, storage and querying for monitoring and observability.',[['What Prometheus is','Prometheus scrapes metrics from targets and stores values as time series with timestamps and labels.'],['Scraping and targets','Configuration defines targets and scrape intervals. Verify target health before interpreting data.'],['PromQL','PromQL selects and aggregates time series; start simple before using rates and complex aggregations.'],['QA and observability','QA can correlate functional behavior with latency, errors and resource metrics during performance, integration and post-deploy validation.'],['Alerts','Useful alert rules should represent actionable conditions rather than noise.'],['Attention point','Metrics require meaningful naming/labels and objectives; excessive cardinality can add cost and complexity.']],'Use metrics as operational evidence to explain system behavior.')
D['prometheus']['es']=L('Prometheus','Colecta, almacenamiento y consulta de métricas de series temporales para monitoreo y observabilidad.',[['Qué es Prometheus','Prometheus obtiene métricas de targets y las almacena como series temporales con timestamps y labels.'],['Scraping y targets','La configuración define targets e intervalos; confirme que el target está saludable antes de interpretar datos.'],['PromQL','PromQL permite seleccionar y agregar series temporales.'],['QA y observabilidad','QA puede correlacionar comportamiento funcional con latencia, errores y recursos.'],['Alertas','Las reglas deben representar condiciones accionables.'],['Punto de atención','Métricas necesitan nombres, labels y objetivos coherentes; cardinalidad excesiva agrega complejidad.']],'Use métricas como evidencia operacional para explicar el comportamiento.')

D['grafana']['pt']=L('Grafana','Dashboards, exploração e correlação de dados de observabilidade a partir de múltiplas fontes.',[
 ['O que é Grafana','Grafana permite consultar e visualizar dados de diferentes fontes em painéis, gráficos e dashboards. Ele não substitui a fonte de dados: conecta-se a sistemas como Prometheus e outros backends.'],['Data Sources','Antes de criar dashboards, configure a fonte de dados e valide conectividade/permissões. A qualidade do painel depende da qualidade e semântica dos dados disponíveis.'],['Dashboards para QA','QA pode acompanhar latência, erros, disponibilidade, filas, consumo de recursos e métricas de negócio durante testes, deploys e investigação de incidentes.'],['Correlação','Um dashboard útil combina contexto: versão, ambiente, janela de tempo e eventos relevantes. Compare métricas com logs/traces e evidências de teste quando necessário.'],['Grafana Open Source e Cloud','Grafana pode ser executado como instância Open Source ou consumido como serviço gerenciado. A escolha muda responsabilidades de instalação, operação e segurança.'],['Ponto de atenção','Dashboard bonito não garante observabilidade. Evite painéis sem objetivo, métricas sem unidade/contexto e alertas que ninguém consegue transformar em ação.']
],'Um dashboard deve responder perguntas operacionais concretas; comece pela pergunta, não pelo gráfico.')
D['grafana']['en']=L('Grafana','Dashboards and exploration of observability data from multiple data sources.',[['What Grafana is','Grafana queries and visualizes data from multiple sources in panels and dashboards; it does not replace the underlying data source.'],['Data Sources','Configure and validate connectivity/permissions before building dashboards.'],['Dashboards for QA','QA can follow latency, errors, availability, queues, resources and business metrics during tests, deployments and incidents.'],['Correlation','Useful dashboards include version, environment, time window and relevant events, and can be correlated with logs/traces and test evidence.'],['Open Source and Cloud','Grafana can run as an open-source instance or as a managed cloud service, changing operational responsibilities.'],['Attention point','A visually attractive dashboard is not observability by itself; every panel and alert should answer an actionable question.']],'Start with the operational question, not the chart type.')
D['grafana']['es']=L('Grafana','Dashboards y exploración de datos de observabilidad desde múltiples fuentes.',[['Qué es Grafana','Grafana consulta y visualiza datos de múltiples fuentes; no reemplaza la fuente subyacente.'],['Data Sources','Configure conectividad y permisos antes de crear dashboards.'],['Dashboards para QA','QA puede seguir latencia, errores, disponibilidad, colas, recursos y métricas de negocio.'],['Correlación','Incluya versión, ambiente, ventana de tiempo y eventos relevantes.'],['Open Source y Cloud','Puede ejecutarse como instancia Open Source o servicio administrado.'],['Punto de atención','Un dashboard bonito no es observabilidad por sí solo; cada panel/alerta debe responder una pregunta accionable.']],'Comience por la pregunta operacional, no por el tipo de gráfico.')

# New topics.
D['wiremock']=topic('🔌','#22c55e','tech','https://wiremock.org/','https://wiremock.org/docs/','https://wiremock.org/docs/download-and-installation/',{
 'pt':L('WireMock','Mocking e service virtualization para controlar dependências HTTP durante testes.',[
  ['O que é WireMock','WireMock cria APIs simuladas para testes e desenvolvimento. Ele ajuda a isolar dependências instáveis, indisponíveis, caras ou ainda não implementadas.'],
  ['Stubs e matching','Um stub define qual request deve ser reconhecida e qual response deve ser devolvida. O matching pode considerar método, URL, headers, query parameters e body.'],
  ['Cenários de erro','Além de respostas de sucesso, simule 4xx/5xx, latência, timeouts, respostas inválidas e comportamentos necessários para validar resiliência.'],
  ['Standalone ou integrado','WireMock pode rodar como JAR/Docker ou ser integrado a testes Java/JVM. Escolha o modo de acordo com isolamento, stack e pipeline.'],
  ['Aplicação em QA','Use mocks para testar o sistema sob condições difíceis de reproduzir com dependências reais, mantendo claro o que foi simulado e o que foi integrado de verdade.'],
  ['Ponto de atenção','Mocks desatualizados podem mascarar incompatibilidades reais. Combine mocking com Contract Testing e testes de integração contra ambientes reais quando necessário.']
 ],'Use mocks para ganhar controle e determinismo, sem esquecer que uma simulação não prova a integração real.'),
 'en':L('WireMock','HTTP mocking and service virtualization for controlled dependencies during testing.',[['What WireMock is','WireMock creates simulated APIs to isolate unstable, unavailable, expensive or not-yet-built dependencies.'],['Stubs and matching','Stubs match requests and return controlled responses using method, URL, headers, query parameters and body.'],['Failure scenarios','Simulate 4xx/5xx, latency, timeouts and malformed responses to validate resilience.'],['Standalone or embedded','Run WireMock as JAR/Docker or integrate it into Java/JVM tests.'],['QA use','Use mocks for hard-to-reproduce conditions while keeping simulated versus real integration explicit.'],['Attention point','Stale mocks can hide real incompatibilities; combine them with contract and integration tests.']],'Use mocks for control and determinism without confusing simulation with real integration.'),
 'es':L('WireMock','Mocking y service virtualization para controlar dependencias HTTP durante pruebas.',[['Qué es WireMock','WireMock crea APIs simuladas para aislar dependencias inestables, indisponibles o aún no implementadas.'],['Stubs y matching','Los stubs reconocen requests y devuelven responses controladas.'],['Escenarios de error','Simule 4xx/5xx, latencia, timeouts y respuestas inválidas.'],['Standalone o integrado','Puede ejecutarse como JAR/Docker o integrado a tests Java/JVM.'],['Uso en QA','Permite reproducir condiciones difíciles de controlar con dependencias reales.'],['Punto de atención','Mocks desactualizados pueden ocultar incompatibilidades; combine con Contract Testing e integración real.']],'Use mocks para control sin confundir simulación con integración real.')})
D['allure-report']=topic('📊','#f59e0b','tech','https://allurereport.org/','https://allurereport.org/docs/','https://allurereport.org/docs/v3/install/',{
 'pt':L('Allure Report','Relatórios interativos de execução de testes para diferentes frameworks e linguagens.',[
  ['O que é Allure Report','Allure transforma resultados produzidos por frameworks de teste em relatórios HTML interativos. Ele é agnóstico de framework e depende de uma integração/adaptador para coletar os resultados.'],
  ['Resultados e evidências','Um bom relatório pode apresentar suites, testes, status, duração, passos, parâmetros e anexos. Screenshots e logs devem ajudar a investigar, não apenas aumentar o volume de evidências.'],
  ['Integração com frameworks','Configure o adaptador adequado para Playwright, Pytest, JUnit, Robot Framework ou outra stack suportada. A instalação do Allure sozinha não coleta automaticamente os resultados do seu framework.'],
  ['Uso em CI/CD','Em pipelines, preserve os artefatos do resultado e publique o relatório de forma acessível ao time. Defina retenção e evite expor segredos em logs/anexos.'],
  ['Histórico e diagnóstico','Quando a integração mantém histórico, tendências ajudam a observar duração, recorrência de falhas e estabilidade da suíte.'],
  ['Ponto de atenção','Relatório sofisticado não corrige testes ruins. Priorize resultados confiáveis, nomes claros e evidências úteis antes de personalizar dashboards.']
 ],'Relatórios devem reduzir o tempo para entender uma falha, não apenas deixar a execução mais bonita.'),
 'en':L('Allure Report','Interactive test execution reporting across frameworks and languages.',[['What Allure Report is','Allure turns test framework results into interactive HTML reports and relies on framework integrations/adapters to collect data.'],['Results and evidence','Use steps, parameters, logs and attachments to support investigation rather than simply adding volume.'],['Framework integration','Configure the adapter for Playwright, Pytest, JUnit, Robot Framework or your supported stack; Allure alone does not collect framework results automatically.'],['CI/CD use','Preserve result artifacts and publish reports securely in pipelines.'],['History and diagnosis','History can help identify duration trends, recurring failures and suite stability.'],['Attention point','A sophisticated report does not fix unreliable tests.']],'A report should reduce time-to-understand a failure, not only look attractive.'),
 'es':L('Allure Report','Reportes interactivos de ejecución de pruebas para diferentes frameworks y lenguajes.',[['Qué es Allure Report','Allure transforma resultados de frameworks en reportes HTML interactivos y depende de adaptadores para colectar datos.'],['Resultados y evidencias','Use pasos, parámetros, logs y adjuntos para apoyar la investigación.'],['Integración','Configure el adaptador para Playwright, Pytest, JUnit, Robot Framework u otra stack soportada.'],['Uso en CI/CD','Preserve artefactos y publique reportes de forma segura.'],['Histórico','El histórico ayuda a observar duración, fallos recurrentes y estabilidad.'],['Punto de atención','Un reporte sofisticado no corrige tests inestables.']],'El reporte debe reducir el tiempo para comprender una falla.')})

json.dump(D,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=2)

# Patch navigation and installable list.
app=ROOT+'/assets/js/app.js'
s=open(app,encoding='utf-8').read()
s=s.replace("{label:{pt:'Tipos de Testes',en:'Testing Types',es:'Tipos de Pruebas'},items:['testing','functional-testing','regression-testing','smoke-testing','sanity-testing','uat','exploratory-testing','integration-testing','e2e-testing','web','mobile','accessibility','localization','ecommerce','payments','visual-regression']},", "{label:{pt:'Tipos de Testes',en:'Testing Types',es:'Tipos de Pruebas'},items:['testing','functional-testing','regression-testing','smoke-testing','sanity-testing','uat','exploratory-testing','integration-testing','e2e-testing','web','mobile','accessibility','localization','ecommerce','payments','visual-regression']},\n  {label:{pt:'Performance',en:'Performance',es:'Performance'},items:['performance','jmeter','k6','gatling','locust','loadrunner']},\n  {label:{pt:'Segurança',en:'Security',es:'Seguridad'},items:['security','owasp','zap','burp-suite']},")
s=s.replace("{label:{pt:'Fundamentos & Testes',en:'Fundamentals & Testing',es:'Fundamentos y Pruebas'},items:['api','http-status','api-auth','rest','graphql','pact']},", "{label:{pt:'Fundamentos & Testes',en:'Fundamentals & Testing',es:'Fundamentos y Pruebas'},items:['api','http-status','api-auth','rest','graphql']},\n  {label:{pt:'Contract Testing',en:'Contract Testing',es:'Contract Testing'},items:['pact']},\n  {label:{pt:'Mocking & Service Virtualization',en:'Mocking & Service Virtualization',es:'Mocking & Service Virtualization'},items:['wiremock']},")
s=s.replace("{label:{pt:'Frameworks & BDD',en:'Frameworks & BDD',es:'Frameworks y BDD'},items:['cucumber','junit','testng']},", "{label:{pt:'Frameworks & BDD',en:'Frameworks & BDD',es:'Frameworks y BDD'},items:['cucumber','junit','testng']},\n  {label:{pt:'Relatórios & Evidências',en:'Reporting & Evidence',es:'Reportes y Evidencias'},items:['allure-report']},")
# Avoid duplicate k6 in automation performance category; keep performance testing in QA & Testing.
s=s.replace("{label:{pt:'Performance Automatizada',en:'Automated Performance',es:'Performance Automatizado'},items:['jmeter','k6','gatling','locust','loadrunner']},", "")
s=s.replace("{label:{pt:'CI/CD',en:'CI/CD',es:'CI/CD'},items:['devops','jenkins','github-actions','bitbucket-pipelines','azure-devops','circleci','release','incidents']},", "{label:{pt:'CI/CD',en:'CI/CD',es:'CI/CD'},items:['devops','jenkins','github-actions','bitbucket-pipelines','azure-devops','circleci','release','incidents']},\n  {label:{pt:'Qualidade de Código',en:'Code Quality',es:'Calidad de Código'},items:['sonarqube']},")
s=s.replace("{label:{pt:'Observabilidade',en:'Observability',es:'Observabilidad'},items:['opentelemetry','grafana','prometheus','datadog','dynatrace','new-relic','sentry']},", "{label:{pt:'Observabilidade & Monitoramento',en:'Observability & Monitoring',es:'Observabilidad y Monitoreo'},items:['opentelemetry','prometheus','grafana','datadog','dynatrace','new-relic','sentry']},")
# Extend installable tools with local tools added/reclassified.
s=s.replace("'proxyman']);", "'proxyman','zap','pact','wiremock','allure-report','sonarqube','prometheus','grafana']);")
# Remove misleading universal installation-guide button from Official resources; installation download remains in the PDF download block only for QA_INSTALLABLE.
s=s.replace("${docs?`<a class=\"btn\" href=\"${docs}\" target=\"_blank\" rel=\"noopener\">📚 ${labels[2]} ↗</a>`:''}<button class=\"btn\" type=\"button\" onclick=\"scrollInstallGuide()\">⚙️ ${guide}</button>", "${docs?`<a class=\"btn\" href=\"${docs}\" target=\"_blank\" rel=\"noopener\">📚 ${labels[2]} ↗</a>`:''}")
open(app,'w',encoding='utf-8').write(s)

# Sitemap: add new routes if missing.
sp=ROOT+'/sitemap.xml'; sm=open(sp,encoding='utf-8').read()
for key in ['wiremock','allure-report']:
    url=f'https://qualityassurancebrasil.com.br/{key}'
    if url not in sm:
        sm=sm.replace('</urlset>',f'  <url>\n    <loc>{url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>')
open(sp,'w',encoding='utf-8').write(sm)

# Master map counts/list.
mp=ROOT+'/data/master-map.json'; M=json.load(open(mp,encoding='utf-8'))
for key in ['wiremock','allure-report']:
    if key not in M.get('implemented_topics',[]): M.setdefault('implemented_topics',[]).append(key)
M['topic_count']=len(D); M['implemented_count']=len(D); M['version']='3.0-final-local'
json.dump(M,open(mp,'w',encoding='utf-8'),ensure_ascii=False,indent=2)
print('topics',len(D))
