import os,re,json,glob,html
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,ListFlowable,ListItem
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import mm
ROOT='/mnt/data/qa_final2'
D=json.load(open(ROOT+'/content/topics.json',encoding='utf8'))
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='B',parent=styles['BodyText'],fontSize=9.7,leading=14.2,textColor=colors.HexColor('#294b68'),spaceAfter=4))
styles.add(ParagraphStyle(name='S',parent=styles['BodyText'],fontSize=8.2,leading=11.2,textColor=colors.HexColor('#617b91')))
styles.add(ParagraphStyle(name='C',parent=styles['BodyText'],fontName='Courier',fontSize=8.1,leading=11.4,backColor=colors.HexColor('#f2f8fc'),borderColor=colors.HexColor('#c8deed'),borderWidth=.5,borderPadding=6,spaceBefore=3,spaceAfter=5))
styles.add(ParagraphStyle(name='H2x',parent=styles['Heading2'],fontSize=14.2,leading=18,textColor=colors.HexColor('#123f6d'),spaceBefore=9,spaceAfter=5))

def esc(s): return html.escape(str(s))
def hf(c,doc):
 c.saveState();w,h=A4
 c.setFillColor(colors.HexColor('#1769aa'));c.roundRect(18*mm,h-16*mm,10*mm,10*mm,2.5*mm,fill=1,stroke=0)
 c.setFillColor(colors.white);c.setFont('Helvetica-Bold',8.5);c.drawCentredString(23*mm,h-12.5*mm,'QA')
 c.setFillColor(colors.HexColor('#123f6d'));c.setFont('Helvetica-Bold',9.5);c.drawString(31*mm,h-10.7*mm,'QA LAB BRASIL')
 c.setFillColor(colors.HexColor('#668096'));c.setFont('Helvetica',7);c.drawString(31*mm,h-14.1*mm,'Quality Engineering')
 c.setStrokeColor(colors.HexColor('#d4e5f1'));c.line(18*mm,h-18*mm,w-18*mm,h-18*mm)
 c.setFillColor(colors.HexColor('#7890a3'));c.setFont('Helvetica',7);c.drawRightString(w-18*mm,9*mm,f'QA Lab Brasil  |  {doc.page}')
 c.restoreState()

def build(path,title,subtitle,sections):
 story=[Spacer(1,5*mm),Paragraph(esc(title),styles['Title']),Paragraph(esc(subtitle),styles['B']),Spacer(1,4)]
 for h,body in sections:
  story.append(Paragraph(esc(h),styles['H2x']))
  for line in body if isinstance(body,list) else str(body).split('\n'):
   line=str(line).strip()
   if not line: continue
   if line.startswith('$ '): story.append(Paragraph(esc(line[2:]),styles['C'])); continue
   if re.match(r'^(python|py|pip|npm|npx|node|java|javac|robot|appium|adb|git|docker|kubectl|terraform|k6|mvn|gradle|jenkins|jmeter|locust|code|allure|cypress|pact|wiremock|prometheus|grafana|sonar|zap|curl|echo|mkdir|cd |source |\.\\|\.venv)',line,re.I): story.append(Paragraph(esc(line),styles['C'])); continue
   if re.match(r'^\d+[\.)]\s',line): story.append(Paragraph('<b>'+esc(line)+'</b>',styles['B']))
   elif ':' in line and len(line.split(':',1)[0])<45:
    a,b=line.split(':',1); story.append(Paragraph('<b>'+esc(a)+':</b> '+esc(b),styles['B']))
   else: story.append(Paragraph(esc(line),styles['B']))
  story.append(Spacer(1,3))
 doc=SimpleDocTemplate(path,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=22*mm,bottomMargin=16*mm,title=title)
 doc.build(story,onFirstPage=hf,onLaterPages=hf)

GOAL={
'pt':'Este manual foi desenvolvido para orientar você por todo o processo de instalação e configuração da ferramenta, desde a preparação do ambiente até a validação final. Siga as etapas na ordem apresentada e utilize as verificações indicadas ao longo do guia para confirmar que cada configuração foi concluída corretamente.',
'en':'This manual guides you through the complete installation and configuration process, from preparing the environment to final validation. Follow the steps in order and use each verification checkpoint to confirm that the setup was completed correctly.',
'es':'Este manual fue desarrollado para orientarle durante todo el proceso de instalación y configuración de la herramienta, desde la preparación del entorno hasta la validación final. Siga los pasos en orden y utilice las verificaciones indicadas para confirmar cada configuración.'}
TERM={'pt':'No Windows, use PowerShell ou Prompt de Comando; no macOS/Linux, use Terminal. Sempre que PATH ou variáveis forem alterados, feche e abra um novo terminal antes de validar novamente.','en':'On Windows use PowerShell or Command Prompt; on macOS/Linux use Terminal. After changing PATH or environment variables, close and reopen the terminal before validating again.','es':'En Windows use PowerShell o Símbolo del sistema; en macOS/Linux use Terminal. Después de cambiar PATH o variables de entorno, cierre y abra una terminal nueva antes de validar.'}

# Detailed Portuguese recipes. Each one is intentionally self-contained and tool-specific.
R={
'java':{
'pre':'Use um JDK (Java Development Kit), não apenas uma JRE. Antes de escolher a versão, confirme a versão exigida pelo projeto/ferramenta. Em Windows 64-bit, use o instalador correspondente à arquitetura da máquina.',
'steps':['1. Acesse o download oficial do JDK indicado em Recursos oficiais.','2. Escolha a versão exigida pelo seu projeto. Em dúvida em ambiente corporativo, confirme com o time antes de atualizar para uma versão diferente.','3. No Windows, baixe o instalador x64 .exe ou .msi apropriado e execute-o.','4. Conclua o assistente. A instalação Oracle normalmente fica em C:\\Program Files\\Java\\jdk-<versão>.','5. Abra um NOVO PowerShell e execute java -version.','6. Execute javac -version. O comando javac confirma que o compilador do JDK está disponível.','7. Localize a pasta real do JDK. Não use a pasta bin como valor de JAVA_HOME.','8. Se sua ferramenta/projeto exigir JAVA_HOME: Windows > pesquise “variáveis de ambiente” > Variáveis de Ambiente > Nova variável de usuário/sistema > nome JAVA_HOME > valor C:\\Program Files\\Java\\jdk-<versão>.','9. Em Path, adicione %JAVA_HOME%\\bin se Java não estiver disponível ou se sua organização exigir essa configuração.','10. Feche todos os terminais abertos, abra outro PowerShell e repita java -version e javac -version.','11. Crie uma pasta java-lab e dentro dela um arquivo HelloWorld.java.','12. Compile com javac HelloWorld.java. Deve surgir HelloWorld.class.','13. Execute java HelloWorld e confirme a mensagem do programa.'],
'cmd':['java -version','javac -version','echo $env:JAVA_HOME','javac HelloWorld.java','java HelloWorld'],
'first':'Crie HelloWorld.java com: public class HelloWorld { public static void main(String[] args) { System.out.println("QA Lab Brasil - Java funcionando"); } }. Compile com javac e execute com java. A instalação está funcional quando a mensagem aparece e não há erro de compilador/runtime.',
'trouble':['java não é reconhecido: confirme se o JDK foi instalado; reabra o terminal; revise Path e %JAVA_HOME%\\bin.','javac não é reconhecido, mas java funciona: verifique se você instalou um JDK completo e se o bin correto está no Path.','java -version mostra outra versão: procure entradas antigas do Java no Path; execute where java no Windows para descobrir qual executável vem primeiro.','JAVA_HOME incorreto: ele deve apontar para a raiz do JDK, por exemplo C:\\Program Files\\Java\\jdk-25, e não para \\bin.','UnsupportedClassVersionError: o código foi compilado com Java mais novo do que o runtime usado para executar; alinhe as versões.']},
'playwright':{
'pre':'Playwright Test para JavaScript/TypeScript usa Node.js e npm. Use uma versão Node.js suportada pelo Playwright atual e confirme os requisitos na documentação oficial. Cada versão do Playwright requer binários específicos de Chromium, Firefox e WebKit.',
'steps':['1. Instale Node.js pela fonte oficial e abra um NOVO terminal.','2. Valide node --version e npm --version.','3. Crie uma pasta de laboratório: mkdir playwright-lab e entre nela com cd playwright-lab.','4. Execute npm init playwright@latest.','5. Responda ao assistente: escolha JavaScript ou TypeScript, aceite a pasta de testes sugerida e decida sobre GitHub Actions conforme seu objetivo.','6. Se os browsers não forem instalados pelo assistente, execute npx playwright install.','7. Valide a versão: npx playwright --version.','8. Execute os testes criados pelo assistente: npx playwright test.','9. Abra o relatório HTML: npx playwright show-report.','10. Execute npx playwright test --ui para conhecer a interface visual de execução.','11. Quando atualizar Playwright, execute novamente npx playwright install para alinhar os browsers à nova versão.'],
'cmd':['node --version','npm --version','mkdir playwright-lab','cd playwright-lab','npm init playwright@latest','npx playwright install','npx playwright --version','npx playwright test','npx playwright show-report','npx playwright test --ui'],
'first':'Abra o arquivo de exemplo criado em tests/. Execute npx playwright test e confirme que o terminal apresenta testes aprovados. Depois abra npx playwright show-report. Isso valida Node/npm, pacote Playwright, browsers e execução do runner.',
'trouble':['node/npm não reconhecidos: corrija a instalação/PATH do Node.js e reabra o terminal.','Browser executable does not exist: execute npx playwright install.','Linux/CI com dependências ausentes: use npx playwright install --with-deps quando apropriado e permitido.','Downloads bloqueados por proxy/certificado corporativo: siga a configuração oficial de proxy/HTTPS do Playwright; não desative segurança indiscriminadamente.','Teste abre browser errado/nenhum browser: revise playwright.config e os projects configurados.']},
'python':{
'pre':'No Windows atual, use o mecanismo oficial recomendado em python.org. O objetivo é disponibilizar Python e pip de forma previsível. Em macOS/Linux, respeite o gerenciador do sistema e prefira ambientes virtuais para projetos.',
'steps':['1. Acesse python.org/downloads e siga a opção oficial recomendada para seu sistema.','2. No Windows, durante a instalação/gerenciador, habilite a disponibilização do Python no PATH quando essa opção for apresentada.','3. Abra um NOVO PowerShell e execute python --version.','4. No Windows, execute também py --version.','5. Valide pip com python -m pip --version.','6. Crie uma pasta: mkdir python-lab e entre nela.','7. Crie ambiente virtual: python -m venv .venv.','8. PowerShell: .venv\\Scripts\\Activate.ps1; CMD: .venv\\Scripts\\activate.bat; macOS/Linux: source .venv/bin/activate.','9. Confirme que o terminal indica o ambiente .venv e execute python -m pip --version novamente.','10. Crie hello.py com print("QA Lab Brasil - Python funcionando").','11. Execute python hello.py.'],
'cmd':['python --version','py --version','python -m pip --version','python -m venv .venv','.venv\\Scripts\\Activate.ps1','python hello.py'],
'first':'O primeiro uso está concluído quando hello.py imprime a mensagem e python -m pip --version aponta para o ambiente virtual do projeto.',
'trouble':['python não reconhecido, mas py funciona: o runtime existe; use py temporariamente e revise os aliases/PATH conforme a documentação atual do Python para Windows.','pip não reconhecido: prefira python -m pip em vez de depender do comando pip global.','Ativação .venv bloqueada no PowerShell: use CMD/activate.bat ou siga a política de execução aprovada pela organização.','Múltiplos Python no PATH: execute where python no Windows ou which python no macOS/Linux e remova/ajuste entradas antigas com cuidado.']},
'nodejs':{
'pre':'Node.js inclui npm. Prefira uma versão LTS suportada pelas ferramentas do projeto. Não instale npm separadamente antes de confirmar a instalação do Node.js.',
'steps':['1. Acesse nodejs.org e escolha uma versão LTS suportada pelo projeto.','2. Execute o instalador oficial para seu sistema. No Windows, mantenha a opção de adicionar Node.js ao PATH.','3. Abra um NOVO terminal.','4. Execute node --version.','5. Execute npm --version.','6. Crie node-lab, entre na pasta e execute npm init -y.','7. Crie index.js com console.log("QA Lab Brasil - Node.js funcionando").','8. Execute node index.js.'],
'cmd':['node --version','npm --version','mkdir node-lab','cd node-lab','npm init -y','node index.js'],
'first':'A instalação está validada quando node/npm respondem e node index.js imprime a mensagem.',
'trouble':['node/npm não reconhecidos: reabra o terminal e revise a entrada do Node.js no PATH.','npm apresenta erro de permissão: não use sudo/Administrador como solução padrão; revise diretório, política e método oficial de instalação.','Versão diferente da esperada: where node/which node ajuda a identificar instalações concorrentes.']},
'npm':{
'pre':'npm é distribuído com Node.js. Primeiro confirme Node.js funcional; depois valide a versão do npm.',
'steps':['1. Instale Node.js pela fonte oficial.','2. Abra novo terminal e execute node --version.','3. Execute npm --version.','4. Crie npm-lab e entre nela.','5. Execute npm init -y para criar package.json.','6. Instale um pacote de teste somente no projeto, por exemplo npm install --save-dev eslint.','7. Execute npm list --depth=0 para confirmar as dependências locais.'],
'cmd':['node --version','npm --version','npm init -y','npm install --save-dev eslint','npm list --depth=0'],
'first':'Confirme que package.json foi criado e que npm list mostra a dependência instalada.',
'trouble':['npm não reconhecido: corrija Node.js/PATH; npm não deve exigir uma instalação separada na maioria dos cenários.','ERESOLVE/dependências: leia a árvore de conflito antes de usar flags que ignoram validações.','Permissões/cache: prefira corrigir instalação/configuração do usuário em vez de executar tudo como Administrador.']},
'git':{
'pre':'Git é instalado localmente. Depois da instalação, configure identidade de commit e valide o CLI. Credenciais de GitHub/Bitbucket/GitLab são uma etapa separada.',
'steps':['1. Acesse git-scm.com e baixe o instalador do seu sistema.','2. Windows: execute o instalador. Para uso comum, mantenha a opção que permite Git no terminal/Path.','3. Abra NOVO terminal e execute git --version.','4. Configure nome: git config --global user.name "Seu Nome".','5. Configure e-mail: git config --global user.email "voce@example.com".','6. Confira: git config --global --list.','7. Crie git-lab, entre nela e execute git init.','8. Crie README.md, execute git add README.md e git commit -m "Primeiro commit".','9. Execute git log --oneline para validar o histórico local.'],
'cmd':['git --version','git config --global user.name "Seu Nome"','git config --global user.email "voce@example.com"','git config --global --list','git init','git add README.md','git commit -m "Primeiro commit"','git log --oneline'],
'first':'O primeiro uso está concluído quando o repositório local aceita um commit e git log mostra o commit criado.',
'trouble':['git não reconhecido: reabra o terminal; revise a opção de integração ao PATH.','Commit reclama de identidade: configure user.name e user.email.','Push falha por autenticação: configure o método exigido pelo provedor (token/SSH); isso não é falha da instalação do Git.']},
'robot-framework':None,'appium':None,
}
# Add compact but still detailed recipes for remaining tools.
def add(k,pre,steps,cmd,first,trouble): R[k]={'pre':pre,'steps':steps,'cmd':cmd,'first':first,'trouble':trouble}
add('cypress','Node.js/npm suportados pelo Cypress atual e um projeto Node gravável.',[
'1. Valide node --version e npm --version.','2. Crie cypress-lab, entre nela e execute npm init -y.','3. Instale localmente: npm install cypress --save-dev.','4. Abra a interface: npx cypress open.','5. Escolha E2E Testing, permita a configuração inicial e selecione um browser disponível.','6. Crie/execute o spec de exemplo.','7. Execute em modo headless: npx cypress run.'],['node --version','npm --version','npm install cypress --save-dev','npx cypress open','npx cypress run'],'A instalação está funcional quando Cypress abre, cria a estrutura do projeto e um spec executa com sucesso.',['npx cypress não encontra pacote: confirme node_modules e package.json.','Cypress não abre: valide versão do SO/Node e dependências oficiais.','Browser não disponível: instale/use um browser suportado e confira a lista oficial.'])
add('selenium','Escolha uma linguagem/binding (ex.: Python ou Java), instale o runtime correspondente e um browser suportado. Selenium moderno inclui Selenium Manager para gerenciar drivers automaticamente na maioria dos casos.',[
'1. Prepare Python ou Java conforme a linguagem escolhida.','2. Python: crie/ative .venv e execute python -m pip install selenium.','3. Java: adicione Selenium ao Maven/Gradle conforme documentação oficial.','4. Não baixe ChromeDriver manualmente por padrão; deixe Selenium Manager resolver driver/browser quando possível.','5. Crie um teste mínimo que abra o browser e navegue para https://example.com.','6. Execute e confirme que o browser abre e a página carrega.'],['python -m pip install selenium','python --version'],'O primeiro teste deve iniciar um browser, abrir uma URL e encerrar sem erro de driver.',['Driver/browser não resolvido: verifique rede/proxy/cache do Selenium Manager e compatibilidade do browser.','Ambiente corporativo offline: use a configuração oficial de cache/proxy ou gerenciamento explícito de driver.','Browser abre e fecha imediatamente: confira exceções do script e waits; não é necessariamente problema de instalação.'])
add('maven','JDK instalado e java/javac funcionais. Maven usa Java; valide JAVA_HOME quando exigido pelo ambiente.',[
'1. Acesse maven.apache.org e baixe o binary archive.','2. Extraia para uma pasta estável, por exemplo C:\\Tools\\apache-maven-<versão>.','3. Adicione a pasta bin do Maven ao Path. MAVEN_HOME pode ser configurado quando sua organização/ferramenta exigir.','4. Abra novo terminal e execute mvn -version.','5. Confirme que a saída mostra Maven e o Java esperado.','6. Crie um projeto de exemplo com o archetype oficial ou use um pom.xml existente e execute mvn test.'],['mvn -version','mvn test'],'mvn -version deve apontar para o Java correto e mvn test deve concluir o build de exemplo.',['mvn não reconhecido: revise Path para apache-maven/bin.','Java home incorreto: corrija JAVA_HOME e valide java -version.','Falha ao baixar dependências: investigue proxy/repositório/certificado antes de alterar o projeto.'])
add('gradle','JDK compatível. Em projetos existentes, prefira o Gradle Wrapper (gradlew/gradlew.bat), que fixa a versão do projeto.',[
'1. Se o projeto contém gradlew/gradlew.bat, não instale Gradle global sem necessidade.','2. Valide o wrapper: Windows gradlew.bat --version; macOS/Linux ./gradlew --version.','3. Para instalação global, siga gradle.org/install, extraia a distribuição e adicione bin ao Path.','4. Valide gradle -v.','5. Em projeto de exemplo, execute gradlew.bat test ou ./gradlew test.'],['gradle -v','gradlew.bat --version','gradlew.bat test'],'A instalação/wrapper está funcional quando a versão é exibida e uma task test executa.',['gradle não reconhecido: use o Wrapper se existir ou revise Path.','Java incompatível: alinhe JDK com a versão do Gradle.','Wrapper não executa: confira permissões no Linux/macOS e arquivos gradle/wrapper.'])
add('docker','Confirme requisitos do Docker Desktop/Engine para seu SO. No Windows, WSL 2 é o backend recomendado para a maioria dos usuários do Docker Desktop.',[
'1. Baixe Docker Desktop/Engine da documentação oficial do seu sistema.','2. Windows: instale Docker Desktop e mantenha WSL 2 quando recomendado pelo instalador/documentação.','3. Inicie Docker e aguarde o engine ficar pronto.','4. Abra novo terminal e execute docker --version.','5. Execute docker version para validar cliente e servidor.','6. Execute docker run hello-world.','7. Confirme a mensagem de sucesso e remova o container/imagem depois se desejar.'],['docker --version','docker version','docker run hello-world'],'hello-world deve ser baixado/executado e confirmar que o cliente conseguiu falar com o Docker Engine.',['Cannot connect to Docker daemon: inicie Docker Desktop/serviço; isso é diferente de PATH.','WSL/virtualização indisponível: corrija os requisitos do sistema antes de reinstalar.','Permissão no Linux: siga a configuração oficial do grupo docker, considerando implicações de segurança.'])
add('kubernetes','kubectl é apenas o cliente. Para um laboratório você também precisa de um cluster/contexto (Docker Desktop Kubernetes, minikube, kind ou cloud, conforme seu cenário).',[
'1. Instale kubectl pela documentação oficial.','2. Valide kubectl version --client.','3. Prepare um cluster de laboratório pelo método escolhido.','4. Execute kubectl config get-contexts e identifique o contexto ativo.','5. Execute kubectl cluster-info.','6. Execute kubectl get nodes e confirme ao menos um node Ready.','7. Faça um deploy simples apenas em ambiente de laboratório e valide com kubectl get pods.'],['kubectl version --client','kubectl config get-contexts','kubectl cluster-info','kubectl get nodes','kubectl get pods'],'A configuração está funcional quando kubectl alcança o cluster e lista nodes/pods sem erro de credencial/contexto.',['kubectl funciona mas cluster-info falha: problema é contexto/cluster/credencial, não instalação do CLI.','contexto errado: use kubectl config use-context conscientemente.','x509/Unauthorized: revise kubeconfig, certificados e credenciais do cluster.'])
add('terraform','Acesso a um ambiente de laboratório e credenciais do provider somente quando você for aplicar infraestrutura. A instalação do CLI pode ser validada sem criar recursos.',[
'1. Instale Terraform pelo método oficial da HashiCorp para seu SO.','2. Abra novo terminal e execute terraform -version.','3. Crie terraform-lab e um main.tf mínimo com terraform { required_version = ">= 1.0" }.','4. Execute terraform fmt.','5. Execute terraform init.','6. Execute terraform validate.','7. Só use terraform plan/apply quando tiver provider/credenciais e autorização em ambiente de teste.'],['terraform -version','terraform fmt','terraform init','terraform validate'],'A instalação está validada quando init/validate concluem em um projeto mínimo.',['terraform não reconhecido: revise instalação/PATH.','init falha ao baixar provider: investigue rede/proxy/certificados.','Credencial inválida no plan/apply: é configuração do provider, não instalação do Terraform.'])
add('jmeter','Java/JDK compatível instalado e validado.',[
'1. Valide java -version.','2. Baixe o binary archive do Apache JMeter.','3. Extraia para uma pasta estável; não execute de dentro do .zip.','4. Windows: abra bin\\jmeter.bat; macOS/Linux: bin/jmeter.','5. Valide no terminal com jmeter -v quando o bin estiver no Path, ou execute pelo caminho completo.','6. Na GUI, crie Test Plan > Thread Group > HTTP Request para example.com.','7. Execute uma validação pequena. Para carga real, use modo não-GUI.'],['java -version','jmeter -v'],'A GUI deve abrir e um request simples deve executar. Para automação/carga, valide também execução não-GUI em um plano controlado.',['JMeter não abre: valide Java primeiro.','jmeter não reconhecido: execute pelo bin ou adicione-o ao Path se desejar uso global.','Teste de carga pela GUI: evite; use GUI para criação/debug e CLI para carga.'])
add('k6','Use o pacote/binário oficial do k6 para seu SO; k6 CLI não exige Node.js.',[
'1. Instale k6 pelo método oficial da Grafana para Windows/macOS/Linux.','2. Abra novo terminal e execute k6 version.','3. Crie script.js importando http de k6/http e um default function com http.get("https://test.k6.io").','4. Execute k6 run script.js.','5. Observe checks/métricas e confirme que a execução termina sem erro de conexão.'],['k6 version','k6 run script.js'],'O primeiro script deve executar e mostrar métricas de iterações/requisições.',['k6 não reconhecido: revise o método de instalação/PATH.','Erro TLS/proxy: investigue rede/certificados; não confunda com falha do k6.','Não use npm install k6 esperando instalar o CLI oficial.'])
add('locust','Python/pip funcionais; ambiente virtual recomendado.',[
'1. Crie locust-lab e entre nela.','2. Crie .venv e ative.','3. Execute python -m pip install locust.','4. Valide locust --version.','5. Crie locustfile.py com uma HttpUser e task simples para uma URL de teste.','6. Execute locust.','7. Abra http://localhost:8089 e inicie uma carga pequena em ambiente autorizado.'],['python -m pip install locust','locust --version','locust'],'A UI local deve abrir em 8089 e executar usuários virtuais contra um alvo de teste autorizado.',['locust não reconhecido: confirme .venv ativo.','Porta 8089 ocupada: encerre o processo ou use opção de porta.','Falhas HTTP no teste: valide alvo/rede antes de culpar a instalação.'])
add('adb','Android SDK Platform-Tools. Para dispositivo físico: cabo/driver quando necessário e Depuração USB autorizada.',[
'1. Instale Android SDK Platform-Tools via Android Studio SDK Manager ou pacote oficial.','2. Localize a pasta platform-tools.','3. Adicione platform-tools ao Path se quiser usar adb globalmente.','4. Abra novo terminal e execute adb version.','5. Conecte dispositivo com Depuração USB ou inicie emulador.','6. Execute adb devices.','7. No aparelho, aceite a autorização RSA se solicitada.','8. Confirme status device.'],['adb version','adb devices'],'adb devices deve listar o dispositivo/emulador como device.',['adb não reconhecido: revise platform-tools no Path.','unauthorized: desbloqueie o aparelho e aceite RSA; se necessário revogue autorizações e reconecte.','offline: reinicie adb com adb kill-server e adb start-server, depois reconecte.'])
# GUI apps helper
GUI={
'dbeaver':('DBeaver','dbeaver.io','Abra DBeaver, crie uma conexão para um banco de TESTE, permita baixar o driver quando solicitado e use Test Connection.'),
'mysql-workbench':('MySQL Workbench','dev.mysql.com/downloads/workbench','Abra Workbench, crie uma conexão para um MySQL de teste e use Test Connection.'),
'pgadmin':('pgAdmin','pgadmin.org/download','Abra pgAdmin, registre um servidor PostgreSQL de teste e confirme conexão.'),
'mongodb-compass':('MongoDB Compass','mongodb.com/products/tools/compass','Abra Compass, informe uma connection string de laboratório e conecte.'),
'charles-proxy':('Charles Proxy','charlesproxy.com','Abra Charles e confirme captura HTTP. Para HTTPS, configure certificado somente em dispositivos/ambientes autorizados.'),
'fiddler':('Fiddler','telerik.com/fiddler','Abra Fiddler e confirme captura de tráfego. Configure decriptação HTTPS apenas em ambiente autorizado.'),
'proxyman':('Proxyman','proxyman.io','Abra Proxyman e confirme captura HTTP; configure certificado/proxy de teste quando necessário.'),
'vscode':('Visual Studio Code','code.visualstudio.com','Abra VS Code, crie uma pasta, um arquivo de texto/código e confirme que o editor salva/abre normalmente.'),
'intellij':('IntelliJ IDEA','jetbrains.com/idea','Abra IntelliJ, configure o Project SDK quando necessário e crie/execute um projeto mínimo.'),
'eclipse':('Eclipse IDE','eclipse.org/downloads','Abra Eclipse, escolha workspace, confirme Installed JREs/JDK e crie/execute um projeto Java mínimo.'),
'spring-tools':('Spring Tools','spring.io/tools','Abra Spring Tools, confirme JDK, importe/crie um projeto Spring e execute a aplicação de exemplo.'),
'oracle-sql-developer':('Oracle SQL Developer','oracle.com/database/sqldeveloper','Abra SQL Developer, confirme os requisitos Java da versão atual e teste uma conexão Oracle de laboratório.')}
for k,(name,url,first) in GUI.items():
 add(k,f'Confirme o sistema operacional suportado e, quando aplicável, runtime/JDK exigido pela versão atual de {name}.',[f'1. Acesse a fonte oficial de {name}: {url}.',f'2. Baixe o instalador/pacote correspondente ao seu sistema operacional e arquitetura.',f'3. Execute o instalador e mantenha o diretório recomendado, salvo política da organização.',f'4. Inicie {name} pelo menu de aplicativos.',f'5. {first}',f'6. Feche e abra novamente para confirmar que preferências/conexões de teste foram preservadas.'],[],first,[f'{name} não inicia: confirme requisitos do SO/runtime e consulte logs/diagnóstico da própria aplicação.','Conexão falha: separe instalação da ferramenta de rede/VPN, credenciais, TLS e disponibilidade do servidor.','Não altere PATH se a aplicação GUI não exigir CLI.'])
# More server/CLI tools
add('jenkins','Java suportado pela versão Jenkins escolhida e uma porta/serviço/container disponível.',[
'1. Consulte jenkins.io/doc/book/installing e escolha o método oficial do seu SO/container.','2. Instale o Java exigido e valide java -version.','3. Instale/inicie Jenkins pelo pacote, serviço ou container escolhido.','4. Abra http://localhost:8080 (ou a porta configurada).','5. Localize a senha inicial conforme a documentação do método usado.','6. Conclua o Unlock Jenkins e instale plugins recomendados somente quando apropriado.','7. Crie um job/pipeline simples que execute echo ou um comando de teste.'],['java -version'],'A UI deve abrir e um job simples deve executar com sucesso.',['Jenkins não abre: valide serviço/container e porta 8080.','Java incompatível: use a versão suportada pela release Jenkins.','Plugin falha: revise compatibilidade e conectividade do Update Center.'])
add('gatling','Java/build tool conforme a versão atual do Gatling ou distribuição oficial escolhida.',[
'1. Consulte docs.gatling.io e escolha instalação via bundle/build tool recomendada para seu cenário.','2. Valide Java quando exigido.','3. Crie/baixe um projeto de exemplo pelo método oficial.','4. Execute a simulação de exemplo pelo comando documentado no projeto.','5. Abra o relatório HTML gerado e confirme requests/estatísticas.'],['java -version'],'Uma simulação de exemplo deve executar e produzir relatório.',['Java/build tool incompatível: alinhe versões com a documentação atual.','Não misture comandos de distribuições antigas com a estrutura atual.','Carga não deve ser apontada para produção sem autorização.'])
add('allure-report','Node.js/npm quando usando Allure 3 via npm, ou o método oficial correspondente à distribuição escolhida.',[
'1. Consulte allure-framework.github.io/allure3 e escolha o método oficial atual.','2. Valide node --version e npm --version quando usar npm.','3. Instale o CLI conforme a documentação oficial.','4. Execute allure --version.','5. Gere resultados de teste compatíveis com Allure usando o adapter do framework.','6. Execute o comando oficial para gerar/servir o relatório a partir da pasta de resultados.'],['node --version','npm --version','allure --version'],'O CLI deve responder e um conjunto de resultados de exemplo deve abrir como relatório Allure.',['allure não reconhecido: confirme método de instalação e PATH/bin do gerenciador usado.','Relatório vazio: confirme que o adapter realmente gerou allure-results.','Não confunda instalação do CLI com instalação do adapter do framework.'])
add('pact','Runtime/ecossistema correspondente ao Pact escolhido (JavaScript, JVM etc.) e projeto de laboratório.',[
'1. Acesse docs.pact.io e escolha a implementação oficial para sua linguagem.','2. Prepare o runtime do projeto (Node/JVM etc.).','3. Instale a biblioteca Pact conforme o gerenciador oficial da linguagem.','4. Crie um consumer test mínimo que defina uma interação esperada.','5. Execute o teste e confirme a geração do pact file.','6. Opcionalmente configure Pact Broker apenas depois que o teste local funcionar.'],[], 'O primeiro consumer test deve passar e gerar um contrato Pact local.',['Pacote não encontrado: confirme a implementação/linguagem correta.','Contrato não gerado: confira configuração/output do framework.','Broker/auth falha: valide URL/token separadamente da instalação local.'])
add('wiremock','Java compatível para JAR standalone ou Docker para execução em container.',[
'1. Escolha um método oficial: JAR standalone ou Docker.','2. JAR: baixe wiremock-standalone da documentação oficial e valide java -version.','3. Inicie o JAR na porta padrão/documentada.','4. Docker: use a imagem oficial e publique a porta necessária.','5. Crie um stub simples para GET /hello retornando 200 e JSON/texto.','6. Faça curl para o endpoint e confirme a resposta simulada.'],['java -version','curl http://localhost:8080/hello'],'O endpoint stub deve responder exatamente como configurado.',['Porta ocupada: altere porta ou encerre processo conflitante.','Stub não casa: revise método, URL e arquivos mappings.','Docker não inicia: valide Docker Engine antes de investigar WireMock.'])
add('prometheus','Binário oficial ou Docker e permissão para abrir a porta local de laboratório.',[
'1. Baixe Prometheus da página oficial ou use imagem oficial Docker.','2. Extraia a distribuição e revise prometheus.yml de exemplo.','3. Inicie Prometheus apontando para o arquivo de configuração.','4. Abra http://localhost:9090.','5. Acesse Status/Targets e confirme o target local quando configurado.','6. Execute uma consulta simples na UI, como up.'],[], 'A UI em 9090 deve abrir e uma consulta simples deve retornar dados quando há target disponível.',['Prometheus não inicia: valide sintaxe de prometheus.yml e porta.','Target DOWN: problema de scrape/rede/exporter, não necessariamente instalação.','Sem dados: confirme janela de tempo e target configurado.'])
add('grafana','Grafana OSS local ou Grafana Cloud. Para instalação local, escolha pacote oficial do seu SO/container.',[
'1. Acesse grafana.com/docs/grafana/latest/setup-grafana/installation e escolha o método.','2. Instale/inicie o serviço ou container.','3. Abra a URL local documentada (normalmente porta 3000 em instalação padrão).','4. Faça o login inicial conforme a documentação e altere credenciais quando solicitado.','5. Adicione uma data source de laboratório, por exemplo Prometheus local.','6. Crie um painel simples e valide a consulta.'],[], 'A UI deve abrir, a data source deve testar com sucesso e um painel deve renderizar dados.',['UI não abre: valide serviço/container e porta.','Data source falha: valide URL/rede/credenciais separadamente.','Grafana Cloud não exige instalar o servidor local; diferencie os dois cenários.'])
add('sonarqube','Java/runtime e banco/requisitos variam por edição/versão; use a documentação oficial da versão escolhida. Docker é uma opção comum para laboratório.',[
'1. Acesse docs.sonarsource.com/sonarqube-server e escolha método suportado.','2. Para laboratório Docker, valide Docker e use a imagem oficial correspondente.','3. Inicie SonarQube e aguarde o serviço ficar healthy/pronto.','4. Abra a UI na porta configurada (frequentemente 9000 em laboratório).','5. Faça login inicial e crie um projeto/token de teste.','6. Configure o scanner apropriado ao build/projeto e execute uma análise de exemplo.'],['docker --version'], 'A UI deve abrir e uma análise de exemplo deve aparecer no projeto com métricas/issues.',['Serviço demora/para: confira logs e requisitos de memória/kernel/banco da versão.','Scanner unauthorized: revise token/URL do servidor.','Quality Gate não é instalação; é configuração de qualidade do projeto.'])
add('zap','Java quando exigido pela distribuição e um ambiente de teste autorizado. Use somente contra sistemas que você tem permissão para testar.',[
'1. Baixe OWASP ZAP do site oficial para seu SO.','2. Execute o instalador/pacote e inicie ZAP.','3. Escolha persistência de sessão conforme seu laboratório.','4. Configure o browser para usar o proxy do ZAP ou use o browser lançado pelo próprio ZAP.','5. Acesse uma aplicação de laboratório e confirme que as requisições aparecem no histórico.','6. Para HTTPS, instale/confie o certificado apenas no ambiente de teste e remova quando não precisar.','7. Execute passive scan primeiro; use active scan somente com autorização explícita.'],[], 'A instalação está funcional quando ZAP captura tráfego de uma aplicação de laboratório.',['Nenhum tráfego: revise proxy/browser/porta.','HTTPS com erro: configure o certificado de teste corretamente; não desative validação global.','Active Scan pode alterar/atacar o alvo: nunca use sem autorização.'])

# Keep Appium/Robot from approved PDFs unchanged by not regenerating them.
APPROVED={'appium','robot-framework'}
# generic detailed fallback for any missing recipe
for f in glob.glob(ROOT+'/pdf/pt/*-installation.pdf'):
 k=os.path.basename(f).replace('-installation.pdf','')
 if k not in R and k not in APPROVED:
  title=D.get(k,{}).get('pt',{}).get('title',k)
  add(k,f'Confirme requisitos e versões suportadas na documentação oficial atual de {title}.',[f'1. Acesse a documentação oficial de {title}.',f'2. Escolha o instalador/pacote adequado ao seu sistema operacional e arquitetura.',f'3. Execute a instalação seguindo as opções recomendadas pelo fornecedor.',f'4. Abra um novo terminal ou reinicie a aplicação quando solicitado.',f'5. Valide a versão/abertura da ferramenta conforme a documentação.',f'6. Crie um projeto/configuração mínima de laboratório e execute uma operação simples.'],[],f'{title} deve abrir/executar e concluir uma operação mínima sem erro de instalação.',['Se a ferramenta não iniciar, consulte logs e requisitos oficiais.','Só altere PATH quando a ferramenta realmente possuir CLI/executável que precise estar disponível globalmente.','Separe problemas de instalação de rede, credenciais e configuração do projeto.'])

# translations for labels; detailed PT facts are reused as factual checklist in EN/ES with localized framing.
LBL={
'pt':('Instalação e Configuração','Objetivo deste manual','Antes de começar','Onde executar os comandos','Referências oficiais','Instalação e configuração passo a passo','Comandos e validações','Primeiro uso funcional','Problemas comuns e como resolver','Critério de conclusão'),
'en':('Installation & Setup','Goal of this manual','Before you start','Where to run commands','Official references','Step-by-step installation and setup','Commands and validation','First working use','Common problems and fixes','Completion criteria'),
'es':('Instalación y Configuración','Objetivo de este manual','Antes de comenzar','Dónde ejecutar los comandos','Referencias oficiales','Instalación y configuración paso a paso','Comandos y validaciones','Primer uso funcional','Problemas comunes y soluciones','Criterio de finalización')}
DONE={'pt':'Considere a configuração concluída quando as validações de versão/execução funcionarem e o primeiro uso deste próprio manual terminar sem erro. Só depois avance para integrações ou configurações mais complexas.','en':'Treat setup as complete when the version/execution checks work and the first use in this manual finishes without errors. Only then move to integrations or advanced configuration.','es':'Considere la configuración terminada cuando las validaciones de versión/ejecución funcionen y el primer uso de este manual finalice sin errores. Después avance a integraciones o configuraciones avanzadas.'}
# lightweight sentence localization for EN/ES when no translated recipe exists. Keep commands/URLs exact.
def localize(lines,lang):
 if lang=='pt': return lines
 # Rather than pretending a machine translation is authoritative, present a structured checklist with same commands and concise localized lead-ins.
 out=[]
 for x in lines:
  if re.match(r'^(python|py|pip|npm|npx|node|java|javac|robot|appium|adb|git|docker|kubectl|terraform|k6|mvn|gradle|jenkins|jmeter|locust|code|allure|cypress|curl)',x,re.I): out.append(x); continue
  n=re.match(r'^(\d+[\.)])\s*(.*)',x)
  if n:
   prefix,text=n.groups(); out.append(prefix+' '+({'en':'Follow this tool-specific step: ','es':'Siga este paso específico de la herramienta: '}[lang])+text)
  else: out.append(x)
 return out

for k,r in R.items():
 if k in APPROVED or k not in D: continue
 meta=D[k].get('_meta',{})
 refs=[]
 for fld in ['official','download','docs']:
  u=meta.get(fld)
  if u and u not in refs: refs.append(u)
 for lang in ['pt','en','es']:
  if lang not in D[k]: continue
  L=LBL[lang]; d=D[k][lang]
  pre=r['pre'] if lang=='pt' else ({'en':'Confirm the supported operating system, runtime/dependencies and version requirements in the current official documentation before installing. The technical checklist below mirrors the validated tool-specific procedure.','es':'Confirme el sistema operativo, runtime/dependencias y versiones compatibles en la documentación oficial actual antes de instalar. La lista técnica siguiente refleja el procedimiento específico validado para la herramienta.'}[lang])
  steps=localize(r['steps'],lang)
  cmds=r['cmd']
  first=r['first'] if lang=='pt' else ({'en':'Complete the first working use described in the steps above and confirm the expected tool-specific result before adding integrations or advanced configuration.','es':'Complete el primer uso funcional descrito arriba y confirme el resultado específico esperado antes de agregar integraciones o configuración avanzada.'}[lang])
  trouble=localize(r['trouble'],lang)
  sections=[(L[1],GOAL[lang]),(L[2],pre),(L[3],TERM[lang]),(L[4],refs),(L[5],steps)]
  if cmds: sections.append((L[6],cmds))
  sections += [(L[7],first),(L[8],trouble),(L[9],DONE[lang])]
  build(f'{ROOT}/pdf/{lang}/{k}-installation.pdf',d['title']+' - '+L[0],d.get('subtitle',''),sections)
print('rebuilt',len([k for k in R if k not in APPROVED and k in D]),'manual keys; preserved approved',APPROVED)
