import os, json, glob, re
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether

ROOT=os.path.dirname(__file__)
D=json.load(open(os.path.join(ROOT,'content/topics.json'),encoding='utf8'))
keys=sorted(os.path.basename(x).replace('-installation.pdf','') for x in glob.glob(os.path.join(ROOT,'pdf/pt/*-installation.pdf')))

# Each tool has explicit verification / first-use commands or actions. The shared prose only explains the novice workflow.
P={
'python':dict(pre='No extra runtime is required.',win='Download the official Windows installer and enable the option that makes Python available from the terminal.',mac='Download the official macOS installer, or use the package method recommended by Python.',linux='Use the distribution package manager or the official Python guidance for your distribution.',verify=['python --version','py --version','py -m pip --version'],setup=['py -m pip install --upgrade pip','py -m venv .venv','.venv\\Scripts\\activate','py -m pip install requests'],unix=['python3 --version','python3 -m pip --version','python3 -m venv .venv','source .venv/bin/activate','python3 -m pip install requests'],first=['python -c "import requests; print(requests.__version__)"'],expect='A Python 3.x version, a pip version, an active .venv environment and the installed requests version.'),
'java':dict(pre='A JDK is required, not only a JRE. Prefer a currently supported LTS JDK for QA tooling unless the project specifies another version.',win='Download a JDK installer from the official vendor page, run it, then configure JAVA_HOME and add %JAVA_HOME%\\bin to PATH when the installer does not do so.',mac='Install a JDK package and confirm /usr/libexec/java_home can locate it.',linux='Install a JDK with the distribution package manager or the vendor package.',verify=['java -version','javac -version'],setup=['echo %JAVA_HOME%','where java'],unix=['echo $JAVA_HOME','which java','java -version','javac -version'],first=['java -version'],expect='java and javac report compatible JDK versions; JAVA_HOME points to the JDK directory.'),
'nodejs':dict(pre='Node.js includes npm. Prefer an LTS release for stable automation environments.',win='Download the official LTS Windows installer and keep npm selected.',mac='Use the official installer or a version manager such as nvm.',linux='Use the official Node.js instructions or a version manager such as nvm.',verify=['node -v','npm -v'],setup=['npm config get prefix'],unix=['node -v','npm -v'],first=['node -e "console.log(\'QA Lab Node OK\')"'],expect='node prints a v-prefixed version and npm prints its version.'),
'npm':dict(pre='Node.js must already be installed because npm is distributed with Node.js.',win='Install Node.js LTS first; npm is installed together with it.',mac='Install Node.js or use nvm; npm follows the active Node.js version.',linux='Install Node.js using the official method or nvm.',verify=['node -v','npm -v'],setup=['npm config get prefix','npm init -y','npm install axios'],unix=['node -v','npm -v','npm init -y','npm install axios'],first=['npm list axios'],expect='npm creates package.json and reports axios in the local dependency tree.'),
'git':dict(pre='No language runtime is required. You will need access to a terminal.',win='Download Git for Windows, run the installer, and keep Git available from the command line.',mac='Install Git using the official installer, Xcode Command Line Tools, or a package manager.',linux='Install git with the distribution package manager.',verify=['git --version'],setup=['git config --global user.name "Your Name"','git config --global user.email "you@example.com"','git config --list'],unix=['git --version','git config --list'],first=['git init qa-lab-git-test'],expect='git reports a version and git init creates a repository without errors.'),
'playwright':dict(pre='Node.js LTS and npm must be available. Python/.NET/Java bindings exist, but this manual validates the Node.js path used by many QA projects.',win='Install Node.js LTS first, then use npm from PowerShell or CMD.',mac='Install Node.js LTS or nvm, then use Terminal.',linux='Install Node.js LTS and the system dependencies required by Playwright browsers.',verify=['node -v','npm -v'],setup=['npm init playwright@latest','npx playwright install'],unix=['npm init playwright@latest','npx playwright install --with-deps'],first=['npx playwright test'],expect='The Playwright test runner starts and reports the generated example test results.'),
'appium':dict(pre='Node.js/npm are required. Android testing also needs Java JDK, Android SDK/platform-tools and a configured device/emulator. iOS automation requires macOS and Xcode.',win='Install Node.js LTS, JDK and Android Studio/SDK. Configure JAVA_HOME and ANDROID_HOME/ANDROID_SDK_ROOT as required by your environment.',mac='Install Node.js, JDK and Android tooling; for iOS install Xcode and its command-line components.',linux='Install Node.js, JDK and Android SDK/platform-tools for Android automation.',verify=['node -v','npm -v','appium -v','adb version'],setup=['npm install -g appium','appium driver install uiautomator2','appium driver list --installed'],unix=['npm install -g appium','appium driver install uiautomator2','appium driver list --installed'],first=['appium'],expect='Appium prints its version, UiAutomator2 appears as installed, and the Appium server starts listening without a startup error.'),
'robot-framework':dict(pre='Python and pip must be installed. Use a virtual environment to isolate project dependencies.',win='Install Python, open PowerShell/CMD in the project folder and create a .venv environment.',mac='Install Python 3 and use Terminal with a virtual environment.',linux='Install Python 3, pip and venv packages for the distribution.',verify=['python --version','python -m pip --version','robot --version'],setup=['python -m venv .venv','.venv\\Scripts\\activate','python -m pip install robotframework'],unix=['python3 -m venv .venv','source .venv/bin/activate','python -m pip install robotframework','robot --version'],first=['robot --version'],expect='Robot Framework reports its version from the active Python environment.'),
'selenium':dict(pre='Choose a language binding. This guide validates Python because it is simple for a first QA setup; modern Selenium Manager can resolve compatible drivers in common scenarios.',win='Install Python and create a virtual environment in the project directory.',mac='Install Python 3 and create a virtual environment.',linux='Install Python 3, pip and venv support.',verify=['python --version','python -m pip --version'],setup=['python -m venv .venv','.venv\\Scripts\\activate','python -m pip install selenium'],unix=['python3 -m venv .venv','source .venv/bin/activate','python -m pip install selenium'],first=['python -c "import selenium; print(selenium.__version__)"'],expect='The selenium package imports successfully and prints its installed version.'),
'cypress':dict(pre='Node.js LTS and npm are required.',win='Install Node.js LTS, then work from PowerShell/CMD in a project folder.',mac='Install Node.js LTS or nvm, then use Terminal.',linux='Install Node.js LTS and any desktop libraries required by Cypress for your distribution.',verify=['node -v','npm -v'],setup=['npm init -y','npm install cypress --save-dev'],unix=['npm init -y','npm install cypress --save-dev'],first=['npx cypress open'],expect='Cypress opens its Launchpad and allows you to choose an E2E or component testing setup.'),
'docker':dict(pre='Hardware virtualization must be enabled when required by your OS. Windows users should confirm WSL 2/virtualization requirements for Docker Desktop.',win='Download Docker Desktop for Windows, install it, restart if requested, and launch Docker Desktop until the engine is running.',mac='Download Docker Desktop for the correct Apple Silicon or Intel architecture and start it.',linux='Install Docker Engine/Desktop using the official repository instructions for your distribution.',verify=['docker --version','docker compose version','docker info'],setup=['docker run --rm hello-world'],unix=['docker --version','docker compose version','docker run --rm hello-world'],first=['docker run --rm hello-world'],expect='Docker downloads/runs hello-world and prints the success message.'),
'adb':dict(pre='ADB is part of Android SDK Platform-Tools. A physical Android device requires USB debugging; an emulator can also be used.',win='Install Android Studio or download Platform-Tools. Ensure the platform-tools directory is on PATH.',mac='Install Android Studio/Platform-Tools and add platform-tools to PATH if needed.',linux='Install Android SDK Platform-Tools and configure device permissions when required.',verify=['adb version','adb devices'],setup=['adb devices'],unix=['adb version','adb devices'],first=['adb shell getprop ro.build.version.release'],expect='adb devices lists the connected emulator/device as device, and the shell command returns an Android version.'),
'allure-report':dict(pre='Java is required. Depending on the installation method, a package manager may also be used.',win='Install Java first, then install Allure using the official Windows method/package manager or archive.',mac='Install Java and Allure using the official macOS method, commonly Homebrew.',linux='Install Java and use the official package/archive instructions for your distribution.',verify=['allure --version','java -version'],setup=['allure --version'],unix=['allure --version','java -version'],first=['allure --version'],expect='Allure and Java both report versions without command-not-found errors.'),
'gradle':dict(pre='A compatible JDK is required. Gradle Wrapper is preferred inside projects.',win='Install a JDK, download Gradle if a global installation is needed, configure GRADLE_HOME if using the binary distribution, and add its bin directory to PATH.',mac='Install a JDK; use the Gradle distribution or a package manager.',linux='Install a JDK and Gradle using the official distribution/package method.',verify=['java -version','gradle -v'],setup=['gradle -v'],unix=['java -version','gradle -v'],first=['gradle init'],expect='Gradle prints version/JVM information and gradle init can create a starter project.'),
'maven':dict(pre='A compatible JDK is required.',win='Install JDK, extract Maven, set MAVEN_HOME if desired and add Maven bin to PATH.',mac='Install JDK and Maven via the official archive or package manager.',linux='Install JDK and Maven through the official archive or distribution package manager.',verify=['java -version','mvn -version'],setup=['mvn -version'],unix=['java -version','mvn -version'],first=['mvn archetype:generate -DgroupId=qa.lab -DartifactId=demo -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false'],expect='mvn -version shows Maven and Java information; the archetype command creates a demo project.'),
'jmeter':dict(pre='Java is required. JMeter is distributed as an archive rather than a traditional installer.',win='Install JDK, download the JMeter binary archive, extract it, then run bin\\jmeter.bat.',mac='Install Java, extract the JMeter archive and run bin/jmeter.',linux='Install Java, extract the JMeter archive and run bin/jmeter.',verify=['java -version','jmeter -v'],setup=['jmeter -v'],unix=['java -version','jmeter -v'],first=['jmeter'],expect='JMeter reports its version; launching jmeter opens the GUI when a graphical environment is available.'),
'k6':dict(pre='No language runtime is required for the k6 binary. Installation method depends on the OS.',win='Install k6 using the official Windows package/repository method.',mac='Install k6 using the official macOS package method.',linux='Add/use the official Grafana k6 repository/package for your distribution.',verify=['k6 version'],setup=['k6 version'],unix=['k6 version'],first=['k6 new qa-lab-test.js','k6 run qa-lab-test.js'],expect='k6 reports its version and executes the generated starter script with a summary.'),
'locust':dict(pre='Python and pip are required. Use a virtual environment.',win='Install Python, create/activate .venv, then install Locust with pip.',mac='Install Python 3, create/activate .venv, then install Locust.',linux='Install Python 3, pip/venv, then install Locust in .venv.',verify=['python --version','locust -V'],setup=['python -m venv .venv','.venv\\Scripts\\activate','python -m pip install locust'],unix=['python3 -m venv .venv','source .venv/bin/activate','python -m pip install locust','locust -V'],first=['locust -V'],expect='Locust prints its installed version from the active virtual environment.'),
'gatling':dict(pre='Use the current official Gatling distribution and its documented Java/runtime requirements.',win='Download/extract the official bundle or use the supported build-tool integration.',mac='Download/extract the bundle or use the supported build-tool integration.',linux='Download/extract the bundle or use the supported build-tool integration.',verify=['java -version'],setup=['java -version'],unix=['java -version'],first=['Use the Gatling launcher/build command supplied by the selected official distribution.'],expect='The Gatling launcher/build starts without Java/runtime errors and can execute a sample simulation.'),
'jenkins':dict(pre='Java is required. For local evaluation you can use the WAR package or an OS-specific package/container.',win='Install a supported JDK, download Jenkins using the official Windows installer or WAR, then start the service/application.',mac='Install a supported JDK and Jenkins using the official package method.',linux='Install Java and Jenkins from the official repository/package for your distribution.',verify=['java -version'],setup=['java -jar jenkins.war --httpPort=8080'],unix=['java -version','java -jar jenkins.war --httpPort=8080'],first=['Open http://localhost:8080 and complete the initial unlock/setup wizard.'],expect='Jenkins starts on port 8080 and displays the initial setup/unlock screen.'),
'kubernetes':dict(pre='For command-line access install kubectl. A local cluster additionally requires a solution such as Docker Desktop Kubernetes, minikube or kind.',win='Install kubectl using the official Windows instructions and optionally enable/create a local cluster.',mac='Install kubectl using the official macOS instructions and optionally create a local cluster.',linux='Install kubectl using the official repository/binary instructions and configure access to a cluster.',verify=['kubectl version --client','kubectl config current-context'],setup=['kubectl version --client'],unix=['kubectl version --client','kubectl config current-context'],first=['kubectl get nodes'],expect='kubectl reports its client version; with a configured cluster, kubectl get nodes returns the cluster nodes.'),
'terraform':dict(pre='Terraform is a standalone CLI. Cloud credentials are only required when you actually provision resources.',win='Install Terraform using the official HashiCorp package/binary method and ensure terraform.exe is on PATH.',mac='Install Terraform using the official HashiCorp repository/package method.',linux='Install Terraform from the official HashiCorp repository/package for your distribution.',verify=['terraform -version'],setup=['terraform -version'],unix=['terraform -version'],first=['terraform -help'],expect='Terraform reports its version and displays command help.'),
'grafana':dict(pre='Grafana can run natively or in Docker. Choose the method appropriate to your environment.',win='Install Grafana using the official Windows package/archive, then start the Grafana service/server.',mac='Install using the official macOS package method or Docker.',linux='Install from the official Grafana repository/package for your distribution.',verify=['grafana server -v'],setup=['grafana server -v'],unix=['grafana server -v'],first=['Open http://localhost:3000 after the server is running.'],expect='Grafana server starts and the web UI responds on the configured port (commonly 3000).'),
'prometheus':dict(pre='Prometheus is distributed as platform-specific binaries and needs a configuration file.',win='Download the official Windows archive, extract it and run prometheus.exe with the included prometheus.yml.',mac='Download/extract the official archive or use the documented package method.',linux='Download/extract the official archive or use the documented package method.',verify=['prometheus --version'],setup=['prometheus --version'],unix=['prometheus --version'],first=['prometheus --config.file=prometheus.yml'],expect='Prometheus starts without configuration errors and its web UI is available on the configured address (commonly port 9090).'),
'sonarqube':dict(pre='SonarQube Server requires a supported Java/database/environment according to the selected edition/version. For evaluation, Docker is often the simplest isolated route.',win='Follow the official SonarQube Server installation method or use Docker Desktop for a local evaluation.',mac='Use the official package/archive or Docker for a local evaluation.',linux='Use the official archive/package or Docker and follow kernel/database prerequisites for production-like use.',verify=['docker --version'],setup=['docker run -d --name sonarqube -p 9000:9000 sonarqube:community'],unix=['docker run -d --name sonarqube -p 9000:9000 sonarqube:community'],first=['Open http://localhost:9000 after the container becomes healthy.'],expect='The SonarQube container remains running and the web UI loads on port 9000.'),
'wiremock':dict(pre='WireMock can run as a standalone Java JAR, Docker container or library. This guide uses the standalone route when Java is available.',win='Install Java, download the standalone WireMock JAR from the official distribution, then run it from PowerShell/CMD.',mac='Install Java, download the standalone JAR and run it from Terminal.',linux='Install Java, download the standalone JAR and run it from the shell.',verify=['java -version'],setup=['java -jar wiremock-standalone.jar --port 8080'],unix=['java -version','java -jar wiremock-standalone.jar --port 8080'],first=['Open http://localhost:8080/__admin/ after the server starts.'],expect='WireMock starts on the selected port and its admin endpoint responds.'),
'zap':dict(pre='OWASP ZAP provides desktop installers/packages and can also run in automation/container modes. Java may be bundled depending on the package.',win='Download the official Windows installer, install ZAP and launch it from the Start menu.',mac='Download the official macOS package and move/install the application as instructed.',linux='Use the official Linux installer/package/container method.',verify=['Launch ZAP and open Help/About to confirm the installed version.'],setup=['Use Quick Start to open a browser or run an automated scan only against systems you are authorized to test.'],unix=['Launch ZAP from the installed package or documented command.'],first=['Open Quick Start and verify the local proxy/browser integration.'],expect='ZAP opens normally and its local proxy/browser integration can be initialized.'),
'vscode':dict(pre='No language runtime is required to install VS Code; extensions may require their own runtimes.',win='Download the official User/System installer and optionally enable Add to PATH / context-menu options.',mac='Download the macOS build for your architecture and move Visual Studio Code to Applications.',linux='Use the official repository/package for your distribution.',verify=['code --version'],setup=['code --version'],unix=['code --version'],first=['code .'],expect='VS Code reports a version and code . opens the current folder when the shell command is installed.'),
'intellij':dict(pre='IntelliJ IDEA can manage project JDKs, but Java projects still require an appropriate JDK.',win='Download the official installer or use JetBrains Toolbox; install and launch IntelliJ IDEA.',mac='Use JetBrains Toolbox or the official macOS package.',linux='Use JetBrains Toolbox, Snap or the official archive as documented.',verify=['Open Help > About and confirm the installed IntelliJ IDEA version.'],setup=['Create a new Java project and select/download a JDK in the project wizard.'],unix=['Launch IntelliJ IDEA and create a Java project.'],first=['Run a Hello World class from the IDE.'],expect='The IDE opens, a JDK is recognized, and a Hello World class runs successfully.'),
'eclipse':dict(pre='A JDK is recommended for Java development. Eclipse packages vary by workload.',win='Download Eclipse Installer, select the package appropriate for Java development and choose a JDK.',mac='Download Eclipse Installer for your architecture and install the desired package.',linux='Download the official installer/archive or use the documented package method.',verify=['Open Help > About Eclipse IDE and confirm the version.'],setup=['Create a Java Project and confirm the installed JRE/JDK in Preferences.'],unix=['Launch Eclipse and create a Java Project.'],first=['Create and run a Hello World class.'],expect='Eclipse opens a workspace, recognizes a JDK and runs the sample class.'),
'spring-tools':dict(pre='A supported JDK is required. Spring Tools can be used as a standalone distribution or extension depending on the selected product.',win='Install a JDK, download Spring Tools from the official Spring page and install/extract it.',mac='Install a JDK and the official Spring Tools package/extension.',linux='Install a JDK and use the official Spring Tools distribution/extension.',verify=['java -version'],setup=['Create a Spring Starter Project from the IDE.'],unix=['java -version'],first=['Run the generated Spring Boot application and observe the startup log.'],expect='The project resolves dependencies and the Spring Boot application starts without configuration errors.'),
}
# GUI/database/proxy tools share explicit launch validation but retain tool-specific official pages and first-use actions.
for k, first, expect in [
('dbeaver','Create a connection profile to a test database and use Test Connection.','DBeaver opens and Test Connection succeeds when valid test credentials are supplied.'),
('mongodb-compass','Create a connection using a non-production MongoDB URI.','Compass opens and can reach the configured test MongoDB instance.'),
('mysql-workbench','Create a connection profile and use Test Connection against a test MySQL instance.','Workbench opens and validates the test connection.'),
('oracle-sql-developer','Configure the required JDK if prompted, then create a test Oracle connection.','SQL Developer opens and can validate a test connection.'),
('pgadmin','Open pgAdmin, set the master password if requested and register a test PostgreSQL server.','pgAdmin opens and can connect to the registered test server.'),
('charles-proxy','Launch Charles, confirm the local proxy port and configure SSL Proxying only for systems you are authorized to inspect.','Charles opens and captures authorized HTTP traffic.'),
('fiddler','Launch Fiddler and confirm traffic capture using an authorized test site.','Fiddler opens and displays captured authorized traffic.'),
('proxyman','Launch Proxyman and follow its certificate/device setup wizard only on devices and systems you are authorized to inspect.','Proxyman opens and captures authorized traffic.'),
]:
 P[k]=dict(pre='This is a desktop application. You may also need access credentials to a non-production system for the first functional validation.',win='Download the official Windows installer from the product page, run it and accept only the components needed for your QA environment.',mac='Download the official macOS package for your architecture and install it according to the vendor instructions.',linux='Use the official Linux package/repository when the product supports Linux; if Linux is not supported, use a supported OS.',verify=[f'Open {D[k]["pt"]["title"]} and confirm the version in its About/Help screen.'],setup=[first],unix=[f'Launch {D[k]["pt"]["title"]} from the installed application/package.'],first=[first],expect=expect)

# Pact can be installed through several ecosystems; validate Node path for a beginner.
P['pact']=dict(pre='Choose the Pact implementation that matches your project language. This guide validates a Node.js project using the Pact JS ecosystem.',win='Install Node.js LTS and npm, then create a test project folder.',mac='Install Node.js LTS/nvm, then create a project folder.',linux='Install Node.js LTS/nvm, then create a project folder.',verify=['node -v','npm -v'],setup=['npm init -y','npm install --save-dev @pact-foundation/pact'],unix=['npm init -y','npm install --save-dev @pact-foundation/pact'],first=['npm list @pact-foundation/pact'],expect='npm lists the Pact package in the project without dependency installation errors.')

# Fill any remaining tool with explicit metadata-derived GUI/CLI workflow, but mark it as vendor-specific rather than inventing commands.
for k in keys:
 if k not in P:
  P[k]=dict(pre='Review the official prerequisites for the current version before installation.',win='Use the official Windows installer/package from the vendor documentation.',mac='Use the official macOS package/instructions for your architecture.',linux='Use the official Linux repository/package/binary instructions for your distribution.',verify=[f'Open {D[k]["pt"]["title"]} or its CLI and confirm the installed version.'],setup=['Complete the vendor setup wizard and keep the default non-production configuration unless your project requires otherwise.'],unix=[f'Launch {D[k]["pt"]["title"]} using the official documented command/package.'],first=['Perform the official getting-started/sample workflow using a non-production target.'],expect='The tool launches without installation errors and completes its official getting-started validation.')


# Final deep-audit localization overrides. These keep OS instructions tool-specific in PT/EN/ES.
OS_LOCAL={
'python':{'pt':('Baixe o instalador oficial do Python para Windows, execute-o e habilite a opção que disponibiliza Python no terminal; depois valide Python e pip.','Baixe o instalador oficial para macOS ou use o método recomendado pelo Python; depois valide python3 e pip.','Instale Python 3 pelo gerenciador da distribuição ou pelo método oficial e confirme também pip e venv.'),'es':('Descargue el instalador oficial de Python para Windows, ejecútelo y habilite la opción que permite usar Python desde el terminal; después valide Python y pip.','Descargue el instalador oficial para macOS o use el método recomendado por Python; después valide python3 y pip.','Instale Python 3 con el gestor de paquetes de la distribución o el método oficial y confirme también pip y venv.')},
'java':{'pt':('Baixe um JDK oficial para Windows, instale-o, configure JAVA_HOME quando necessário e adicione %JAVA_HOME%\\bin ao PATH.','Instale um JDK para macOS e confirme que /usr/libexec/java_home localiza a instalação.','Instale um JDK pelo gerenciador da distribuição ou pacote do fornecedor e valide java e javac.'),'es':('Descargue un JDK oficial para Windows, instálelo, configure JAVA_HOME cuando sea necesario y agregue %JAVA_HOME%\\bin al PATH.','Instale un JDK para macOS y confirme que /usr/libexec/java_home localiza la instalación.','Instale un JDK mediante el gestor de la distribución o el paquete del proveedor y valide java y javac.')},
'nodejs':{'pt':('Baixe o instalador LTS oficial do Node.js para Windows e mantenha npm selecionado durante a instalação.','Use o instalador oficial ou nvm para instalar uma versão LTS do Node.js.','Use as instruções oficiais do Node.js ou nvm para instalar uma versão LTS na distribuição.'),'es':('Descargue el instalador LTS oficial de Node.js para Windows y mantenga npm seleccionado durante la instalación.','Use el instalador oficial o nvm para instalar una versión LTS de Node.js.','Use las instrucciones oficiales de Node.js o nvm para instalar una versión LTS en la distribución.')},
'npm':{'pt':('Instale primeiro o Node.js LTS; npm é instalado junto com ele.','Instale Node.js ou use nvm; npm acompanha a versão ativa do Node.js.','Instale Node.js pelo método oficial ou nvm; npm será disponibilizado junto com ele.'),'es':('Instale primero Node.js LTS; npm se instala junto con él.','Instale Node.js o use nvm; npm acompaña la versión activa de Node.js.','Instale Node.js mediante el método oficial o nvm; npm quedará disponible junto con él.')},
'git':{'pt':('Baixe Git for Windows, execute o instalador e mantenha a opção que disponibiliza Git no terminal.','Instale Git pelo instalador oficial, Xcode Command Line Tools ou gerenciador de pacotes.','Instale git pelo gerenciador de pacotes da distribuição e valide no terminal.'),'es':('Descargue Git for Windows, ejecute el instalador y mantenga la opción que permite usar Git desde el terminal.','Instale Git mediante el instalador oficial, Xcode Command Line Tools o un gestor de paquetes.','Instale git mediante el gestor de paquetes de la distribución y valídelo en el terminal.')},
'playwright':{'pt':('Instale Node.js LTS e npm; depois abra PowerShell/CMD na pasta do projeto para inicializar Playwright.','Instale Node.js LTS ou nvm e use o Terminal para inicializar o projeto Playwright.','Instale Node.js LTS e as dependências de sistema exigidas pelos navegadores do Playwright.'),'es':('Instale Node.js LTS y npm; después abra PowerShell/CMD en la carpeta del proyecto para inicializar Playwright.','Instale Node.js LTS o nvm y use Terminal para inicializar el proyecto Playwright.','Instale Node.js LTS y las dependencias del sistema requeridas por los navegadores de Playwright.')},
'appium':{'pt':('Instale Node.js LTS, JDK e Android Studio/SDK; configure JAVA_HOME e ANDROID_HOME/ANDROID_SDK_ROOT e confirme adb antes de instalar Appium.','Instale Node.js, JDK e ferramentas Android; para iOS instale Xcode e componentes de linha de comando.','Instale Node.js, JDK e Android SDK/platform-tools para automação Android.'),'es':('Instale Node.js LTS, JDK y Android Studio/SDK; configure JAVA_HOME y ANDROID_HOME/ANDROID_SDK_ROOT y confirme adb antes de instalar Appium.','Instale Node.js, JDK y herramientas Android; para iOS instale Xcode y sus componentes de línea de comandos.','Instale Node.js, JDK y Android SDK/platform-tools para automatización Android.')},
'robot-framework':{'pt':('Instale Python, abra PowerShell/CMD na pasta do projeto, crie .venv, ative-o e instale robotframework com pip.','Instale Python 3, crie e ative .venv no Terminal e instale robotframework com pip.','Instale Python 3, pip e suporte a venv; crie/ative .venv e instale robotframework.'),'es':('Instale Python, abra PowerShell/CMD en la carpeta del proyecto, cree .venv, actívelo e instale robotframework con pip.','Instale Python 3, cree y active .venv en Terminal e instale robotframework con pip.','Instale Python 3, pip y soporte para venv; cree/active .venv e instale robotframework.')},
'selenium':{'pt':('Instale Python, crie um ambiente virtual na pasta do projeto e instale selenium com pip.','Instale Python 3, crie/ative um ambiente virtual e instale selenium com pip.','Instale Python 3, pip e venv; crie/ative o ambiente e instale selenium.'),'es':('Instale Python, cree un entorno virtual en la carpeta del proyecto e instale selenium con pip.','Instale Python 3, cree/active un entorno virtual e instale selenium con pip.','Instale Python 3, pip y venv; cree/active el entorno e instale selenium.')},
'cypress':{'pt':('Instale Node.js LTS e npm, abra PowerShell/CMD em uma pasta de projeto e instale Cypress como dependência de desenvolvimento.','Instale Node.js LTS ou nvm, abra o Terminal na pasta do projeto e instale Cypress.','Instale Node.js LTS e as bibliotecas de desktop exigidas pelo Cypress na sua distribuição.'),'es':('Instale Node.js LTS y npm, abra PowerShell/CMD en una carpeta de proyecto e instale Cypress como dependencia de desarrollo.','Instale Node.js LTS o nvm, abra Terminal en la carpeta del proyecto e instale Cypress.','Instale Node.js LTS y las bibliotecas de escritorio requeridas por Cypress en su distribución.')},
'docker':{'pt':('Baixe Docker Desktop para Windows, instale, reinicie se solicitado e aguarde o engine ficar ativo; confirme requisitos de WSL 2/virtualização.','Baixe Docker Desktop para Apple Silicon ou Intel conforme o Mac, instale e inicie o engine.','Instale Docker Engine/Desktop usando o repositório oficial da sua distribuição e valide o daemon.'),'es':('Descargue Docker Desktop para Windows, instálelo, reinicie si se solicita y espere a que el engine esté activo; confirme requisitos de WSL 2/virtualización.','Descargue Docker Desktop para Apple Silicon o Intel según el Mac, instálelo e inicie el engine.','Instale Docker Engine/Desktop usando el repositorio oficial de su distribución y valide el daemon.')},
'adb':{'pt':('Instale Android Studio ou baixe Platform-Tools e adicione platform-tools ao PATH; habilite Depuração USB no dispositivo quando usar aparelho físico.','Instale Android Studio/Platform-Tools e adicione platform-tools ao PATH se necessário.','Instale Android SDK Platform-Tools e configure permissões do dispositivo quando exigido pela distribuição.'),'es':('Instale Android Studio o descargue Platform-Tools y agregue platform-tools al PATH; habilite Depuración USB al usar un dispositivo físico.','Instale Android Studio/Platform-Tools y agregue platform-tools al PATH si es necesario.','Instale Android SDK Platform-Tools y configure los permisos del dispositivo cuando la distribución lo requiera.')},
'maven':{'pt':('Instale um JDK, extraia Maven, configure MAVEN_HOME se desejar e adicione a pasta bin do Maven ao PATH.','Instale JDK e Maven pelo arquivo oficial ou gerenciador de pacotes.','Instale JDK e Maven pelo arquivo oficial ou gerenciador da distribuição.'),'es':('Instale un JDK, extraiga Maven, configure MAVEN_HOME si lo desea y agregue la carpeta bin de Maven al PATH.','Instale JDK y Maven mediante el archivo oficial o un gestor de paquetes.','Instale JDK y Maven mediante el archivo oficial o el gestor de la distribución.')},
'gradle':{'pt':('Instale JDK, baixe Gradle se precisar de instalação global, configure GRADLE_HOME e adicione bin ao PATH.','Instale JDK e Gradle pela distribuição oficial ou gerenciador de pacotes.','Instale JDK e Gradle pelo método oficial ou gerenciador da distribuição.'),'es':('Instale JDK, descargue Gradle si necesita una instalación global, configure GRADLE_HOME y agregue bin al PATH.','Instale JDK y Gradle mediante la distribución oficial o un gestor de paquetes.','Instale JDK y Gradle mediante el método oficial o el gestor de la distribución.')},
'jmeter':{'pt':('Instale JDK, baixe o arquivo binário do JMeter, extraia e execute bin\\jmeter.bat.','Instale Java, extraia o arquivo JMeter e execute bin/jmeter.','Instale Java, extraia o arquivo JMeter e execute bin/jmeter.'),'es':('Instale JDK, descargue el archivo binario de JMeter, extráigalo y ejecute bin\\jmeter.bat.','Instale Java, extraiga el archivo de JMeter y ejecute bin/jmeter.','Instale Java, extraiga el archivo de JMeter y ejecute bin/jmeter.')},
'k6':{'pt':('Instale k6 pelo método oficial para Windows e valide o executável no terminal.','Instale k6 pelo método oficial para macOS e valide no Terminal.','Adicione/use o repositório oficial Grafana k6 para sua distribuição e instale o pacote.'),'es':('Instale k6 mediante el método oficial para Windows y valide el ejecutable en el terminal.','Instale k6 mediante el método oficial para macOS y valídelo en Terminal.','Agregue/use el repositorio oficial de Grafana k6 para su distribución e instale el paquete.')},
'locust':{'pt':('Instale Python, crie/ative .venv e instale Locust com pip.','Instale Python 3, crie/ative .venv e instale Locust.','Instale Python 3, pip/venv, crie o ambiente e instale Locust.'),'es':('Instale Python, cree/active .venv e instale Locust con pip.','Instale Python 3, cree/active .venv e instale Locust.','Instale Python 3, pip/venv, cree el entorno e instale Locust.')},
'gatling':{'pt':('Baixe e extraia o bundle oficial do Gatling ou use a integração suportada com ferramenta de build.','Baixe/extraia o bundle ou use a integração suportada com ferramenta de build.','Baixe/extraia o bundle ou use a integração suportada com ferramenta de build.'),'es':('Descargue y extraiga el bundle oficial de Gatling o use la integración compatible con una herramienta de build.','Descargue/extraiga el bundle o use la integración compatible con una herramienta de build.','Descargue/extraiga el bundle o use la integración compatible con una herramienta de build.')},
'kubernetes':{'pt':('Instale kubectl pelas instruções oficiais do Windows e, se necessário, crie/habilite um cluster local.','Instale kubectl pelas instruções oficiais do macOS e configure acesso a um cluster.','Instale kubectl pelo repositório/binário oficial e configure o kubeconfig para acessar um cluster.'),'es':('Instale kubectl siguiendo las instrucciones oficiales de Windows y, si es necesario, cree/habilite un clúster local.','Instale kubectl siguiendo las instrucciones oficiales de macOS y configure el acceso a un clúster.','Instale kubectl mediante el repositorio/binario oficial y configure kubeconfig para acceder a un clúster.')},
'prometheus':{'pt':('Baixe o arquivo oficial para Windows, extraia e execute prometheus.exe usando o prometheus.yml incluído.','Baixe/extraia o arquivo oficial ou use o método de pacote documentado.','Baixe/extraia o arquivo oficial ou use o método de pacote documentado para sua distribuição.'),'es':('Descargue el archivo oficial para Windows, extráigalo y ejecute prometheus.exe usando el prometheus.yml incluido.','Descargue/extraiga el archivo oficial o use el método de paquete documentado.','Descargue/extraiga el archivo oficial o use el método de paquete documentado para su distribución.')},
'grafana':{'pt':('Instale Grafana pelo pacote/arquivo oficial para Windows e inicie o serviço/servidor Grafana.','Instale pelo método oficial para macOS ou use Docker e inicie o servidor.','Instale pelo repositório/pacote oficial Grafana da distribuição e inicie o serviço.'),'es':('Instale Grafana mediante el paquete/archivo oficial para Windows e inicie el servicio/servidor Grafana.','Instale mediante el método oficial para macOS o use Docker e inicie el servidor.','Instale mediante el repositorio/paquete oficial de Grafana para la distribución e inicie el servicio.')},
'jenkins':{'pt':('Instale um JDK suportado, baixe Jenkins pelo instalador Windows ou WAR oficial e inicie o serviço/aplicação.','Instale JDK suportado e Jenkins pelo método oficial para macOS.','Instale Java e Jenkins pelo repositório/pacote oficial da distribuição.'),'es':('Instale un JDK compatible, descargue Jenkins mediante el instalador de Windows o WAR oficial e inicie el servicio/aplicación.','Instale un JDK compatible y Jenkins mediante el método oficial para macOS.','Instale Java y Jenkins mediante el repositorio/paquete oficial de la distribución.')},
'sonarqube':{'pt':('Para avaliação local, instale Docker Desktop e execute a imagem Community; para instalação nativa siga os pré-requisitos oficiais do SonarQube Server.','Use o pacote/arquivo oficial ou Docker para uma avaliação local.','Use arquivo/pacote oficial ou Docker; para uso semelhante a produção, siga também pré-requisitos de kernel e banco de dados.'),'es':('Para evaluación local, instale Docker Desktop y ejecute la imagen Community; para instalación nativa siga los prerrequisitos oficiales de SonarQube Server.','Use el paquete/archivo oficial o Docker para una evaluación local.','Use archivo/paquete oficial o Docker; para un uso similar a producción, siga también los prerrequisitos de kernel y base de datos.')},
'terraform':{'pt':('Baixe/instale Terraform pelo método oficial HashiCorp para Windows e garanta que terraform.exe esteja no PATH.','Instale Terraform pelo repositório/pacote oficial HashiCorp para macOS.','Instale Terraform pelo repositório/pacote oficial HashiCorp da sua distribuição.'),'es':('Descargue/instale Terraform mediante el método oficial de HashiCorp para Windows y asegúrese de que terraform.exe esté en PATH.','Instale Terraform mediante el repositorio/paquete oficial de HashiCorp para macOS.','Instale Terraform mediante el repositorio/paquete oficial de HashiCorp para su distribución.')},
'vscode':{'pt':('Baixe o instalador User/System oficial; durante a instalação habilite Add to PATH e, se desejar, as opções de menu de contexto.','Baixe a versão para Apple Silicon ou Intel e mova Visual Studio Code para Applications; depois habilite o comando code pelo Command Palette se necessário.','Instale pelo repositório/pacote oficial da sua distribuição e valide o comando code.'),'es':('Descargue el instalador User/System oficial; durante la instalación habilite Add to PATH y, si lo desea, las opciones del menú contextual.','Descargue la versión para Apple Silicon o Intel y mueva Visual Studio Code a Applications; después habilite el comando code desde Command Palette si es necesario.','Instale mediante el repositorio/paquete oficial de su distribución y valide el comando code.')},
'wiremock':{'pt':('Instale Java, baixe o JAR standalone oficial do WireMock e execute-o pelo PowerShell/CMD.','Instale Java, baixe o JAR standalone e execute pelo Terminal.','Instale Java, baixe o JAR standalone e execute pelo shell.'),'es':('Instale Java, descargue el JAR standalone oficial de WireMock y ejecútelo desde PowerShell/CMD.','Instale Java, descargue el JAR standalone y ejecútelo desde Terminal.','Instale Java, descargue el JAR standalone y ejecútelo desde el shell.')},
'zap':{'pt':('Baixe o instalador oficial do ZAP para Windows, instale e inicie pelo menu Iniciar.','Baixe o pacote oficial para macOS e instale/mova o aplicativo conforme indicado.','Use o instalador/pacote/container oficial para Linux.'),'es':('Descargue el instalador oficial de ZAP para Windows, instálelo e inícielo desde el menú Inicio.','Descargue el paquete oficial para macOS e instale/mueva la aplicación según las instrucciones.','Use el instalador/paquete/contenedor oficial para Linux.')},
'eclipse':{'pt':('Baixe Eclipse Installer, escolha o pacote adequado ao desenvolvimento Java e selecione um JDK.','Baixe Eclipse Installer para sua arquitetura e instale o pacote desejado.','Baixe o instalador/arquivo oficial ou use o método de pacote documentado.'),'es':('Descargue Eclipse Installer, elija el paquete adecuado para desarrollo Java y seleccione un JDK.','Descargue Eclipse Installer para su arquitectura e instale el paquete deseado.','Descargue el instalador/archivo oficial o use el método de paquete documentado.')},
'intellij':{'pt':('Baixe o instalador oficial ou JetBrains Toolbox, instale e inicie IntelliJ IDEA.','Use JetBrains Toolbox ou o pacote oficial para macOS.','Use JetBrains Toolbox, Snap ou o arquivo oficial conforme documentado.'),'es':('Descargue el instalador oficial o JetBrains Toolbox, instale e inicie IntelliJ IDEA.','Use JetBrains Toolbox o el paquete oficial para macOS.','Use JetBrains Toolbox, Snap o el archivo oficial según la documentación.')},
'spring-tools':{'pt':('Instale um JDK, baixe Spring Tools da página oficial Spring e instale/extraia o pacote.','Instale JDK e o pacote/extensão oficial Spring Tools.','Instale JDK e use a distribuição/extensão oficial Spring Tools.'),'es':('Instale un JDK, descargue Spring Tools desde la página oficial de Spring e instale/extraiga el paquete.','Instale JDK y el paquete/extensión oficial de Spring Tools.','Instale JDK y use la distribución/extensión oficial de Spring Tools.')},
'allure-report':{'pt':('Instale Java e depois Allure pelo método oficial para Windows, gerenciador de pacotes ou arquivo.','Instale Java e Allure pelo método oficial para macOS, normalmente via Homebrew.','Instale Java e use o pacote/arquivo oficial do Allure para sua distribuição.'),'es':('Instale Java y después Allure mediante el método oficial para Windows, gestor de paquetes o archivo.','Instale Java y Allure mediante el método oficial para macOS, normalmente con Homebrew.','Instale Java y use el paquete/archivo oficial de Allure para su distribución.')},
'pact':{'pt':('Instale Node.js LTS e npm e crie uma pasta de projeto para validar Pact JS.','Instale Node.js LTS/nvm e crie uma pasta de projeto.','Instale Node.js LTS/nvm e crie uma pasta de projeto.'),'es':('Instale Node.js LTS y npm y cree una carpeta de proyecto para validar Pact JS.','Instale Node.js LTS/nvm y cree una carpeta de proyecto.','Instale Node.js LTS/nvm y cree una carpeta de proyecto.')},
}
# GUI/database/proxy tools: explicit beginner workflows rather than generic fallback.
GUI_LOCAL={
'dbeaver':('Baixe e instale DBeaver Community; abra o aplicativo, crie uma conexão para um banco de teste, informe host/porta/banco/usuário e use Test Connection.','Descargue e instale DBeaver Community; abra la aplicación, cree una conexión a una base de prueba, informe host/puerto/base/usuario y use Test Connection.'),
'mongodb-compass':('Baixe e instale MongoDB Compass; abra o aplicativo e conecte usando uma URI de MongoDB não produtiva.','Descargue e instale MongoDB Compass; abra la aplicación y conéctese usando una URI de MongoDB no productiva.'),
'mysql-workbench':('Baixe e instale MySQL Workbench; crie uma conexão de teste, informe host/porta/usuário e execute Test Connection.','Descargue e instale MySQL Workbench; cree una conexión de prueba, informe host/puerto/usuario y ejecute Test Connection.'),
'oracle-sql-developer':('Baixe SQL Developer, configure o JDK se solicitado e crie uma conexão Oracle de teste.','Descargue SQL Developer, configure el JDK si se solicita y cree una conexión Oracle de prueba.'),
'pgadmin':('Baixe e instale pgAdmin; defina a senha mestra se solicitada e registre um servidor PostgreSQL de teste.','Descargue e instale pgAdmin; defina la contraseña maestra si se solicita y registre un servidor PostgreSQL de prueba.'),
'charles-proxy':('Baixe e instale Charles; inicie o proxy, confirme a porta local e configure SSL Proxying apenas em sistemas autorizados.','Descargue e instale Charles; inicie el proxy, confirme el puerto local y configure SSL Proxying solo en sistemas autorizados.'),
'fiddler':('Baixe e instale Fiddler; abra o aplicativo e valide a captura usando somente um site/ambiente de teste autorizado.','Descargue e instale Fiddler; abra la aplicación y valide la captura usando únicamente un sitio/entorno de prueba autorizado.'),
'proxyman':('Baixe e instale Proxyman; siga o assistente de certificado/dispositivo somente em sistemas autorizados e valide uma captura de teste.','Descargue e instale Proxyman; siga el asistente de certificado/dispositivo solo en sistemas autorizados y valide una captura de prueba.'),
}
for _k,(_pt,_es) in GUI_LOCAL.items():
    OS_LOCAL[_k]={'pt':(_pt,_pt,_pt),'es':(_es,_es,_es)}

T={
'pt':dict(title='Instalação e Configuração Completa',aud='Guia para iniciantes - do download ao primeiro uso',objective='Objetivo',obj='Ao final deste manual, você deverá conseguir instalar a ferramenta, validar a instalação, executar o primeiro uso e reconhecer os erros mais comuns. Não pule as validações: elas confirmam se cada etapa realmente funcionou.',before='Antes de começar',official='Download e documentação oficial',windows='Windows - passo a passo',mac='macOS - passo a passo',linux='Linux - passo a passo',terminal='Abra o terminal correto',terminal_text='No Windows, use CMD ou PowerShell. No macOS e Linux, use o Terminal. Execute os comandos exatamente como aparecem e pressione Enter após cada linha.',verify='Validar a instalação',commands='Comandos e configuração',first='Primeiro uso / teste funcional',expected='Resultado esperado',trouble='Troubleshooting',check='Checklist final',attention='Atenção',att='Use apenas ambientes, contas e dispositivos de teste quando a ferramenta puder capturar tráfego, executar scans, alterar infraestrutura ou acessar dados. Em ambiente corporativo, siga as políticas da organização.',next='O que fazer se não funcionar?',nexttxt='Leia a mensagem exibida no terminal antes de repetir comandos. Confirme PATH/variáveis, versão do runtime, permissões, arquitetura do sistema e se você abriu um novo terminal após alterar variáveis.',done='Instalação validada. Guarde este manual para reinstalações, onboarding e troubleshooting.'),
'en':dict(title='Complete Installation & Setup',aud='Beginner guide - from download to first use',objective='Objective',obj='By the end of this manual, you should be able to install the tool, validate the installation, perform the first functional use and recognize common errors. Do not skip validation steps: they confirm that each stage actually worked.',before='Before you start',official='Official download and documentation',windows='Windows - step by step',mac='macOS - step by step',linux='Linux - step by step',terminal='Open the correct terminal',terminal_text='On Windows, use CMD or PowerShell. On macOS and Linux, use Terminal. Run commands exactly as shown and press Enter after each line.',verify='Validate the installation',commands='Commands and configuration',first='First use / functional test',expected='Expected result',trouble='Troubleshooting',check='Final checklist',attention='Attention',att='Use only test environments, accounts and devices when a tool can capture traffic, run scans, modify infrastructure or access data. In corporate environments, follow your organization policies.',next='What if it does not work?',nexttxt='Read the terminal error before repeating commands. Check PATH/environment variables, runtime version, permissions, system architecture and whether a new terminal was opened after environment changes.',done='Installation validated. Keep this manual for reinstallations, onboarding and troubleshooting.'),
'es':dict(title='Instalación y Configuración Completa',aud='Guía para principiantes - desde la descarga hasta el primer uso',objective='Objetivo',obj='Al finalizar este manual, deberá poder instalar la herramienta, validar la instalación, realizar el primer uso funcional y reconocer los errores más comunes. No omita las validaciones: confirman que cada etapa realmente funcionó.',before='Antes de comenzar',official='Descarga y documentación oficial',windows='Windows - paso a paso',mac='macOS - paso a paso',linux='Linux - paso a paso',terminal='Abra el terminal correcto',terminal_text='En Windows, use CMD o PowerShell. En macOS y Linux, use Terminal. Ejecute los comandos exactamente como aparecen y presione Enter después de cada línea.',verify='Validar la instalación',commands='Comandos y configuración',first='Primer uso / prueba funcional',expected='Resultado esperado',trouble='Solución de problemas',check='Checklist final',attention='Atención',att='Utilice únicamente entornos, cuentas y dispositivos de prueba cuando una herramienta pueda capturar tráfico, ejecutar escaneos, modificar infraestructura o acceder a datos. En entornos corporativos, siga las políticas de su organización.',next='¿Qué hacer si no funciona?',nexttxt='Lea el error mostrado en el terminal antes de repetir comandos. Verifique PATH/variables de entorno, versión del runtime, permisos, arquitectura del sistema y si abrió un nuevo terminal después de cambiar variables.',done='Instalación validada. Conserve este manual para reinstalaciones, onboarding y troubleshooting.')}

styles=getSampleStyleSheet()
H1=ParagraphStyle('H1',parent=styles['Heading1'],fontName='Helvetica-Bold',fontSize=18,leading=22,textColor=colors.HexColor('#0b3b6e'),spaceAfter=8)
H2=ParagraphStyle('H2',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=12.5,leading=16,textColor=colors.HexColor('#174f8d'),spaceBefore=10,spaceAfter=5)
B=ParagraphStyle('B',parent=styles['BodyText'],fontName='Helvetica',fontSize=9.5,leading=13.5,textColor=colors.HexColor('#263b53'),spaceAfter=6)
CODE=ParagraphStyle('CODE',parent=B,fontName='Courier',fontSize=8.5,leading=12,backColor=colors.HexColor('#f3f8fc'),borderColor=colors.HexColor('#c7deef'),borderWidth=.5,borderPadding=7,spaceAfter=5)
SM=ParagraphStyle('SM',parent=B,fontSize=8.3,leading=11,textColor=colors.HexColor('#587089'))
CALLOUT=ParagraphStyle('CALLOUT',parent=B,backColor=colors.HexColor('#eef7ff'),borderColor=colors.HexColor('#8fc3e8'),borderWidth=.7,borderPadding=8,spaceBefore=4,spaceAfter=8)
WARN=ParagraphStyle('WARN',parent=B,backColor=colors.HexColor('#fff8e7'),borderColor=colors.HexColor('#f1c86b'),borderWidth=.7,borderPadding=8,spaceBefore=4,spaceAfter=8)

def esc(s): return str(s).replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
def localized(s,lang):
 # Explicit localization for common profile prose. Tool names/commands remain unchanged.
 if lang=='pt':
  mp={'No extra runtime is required.':'Nenhum runtime adicional é necessário.','A JDK is required, not only a JRE. Prefer a currently supported LTS JDK for QA tooling unless the project specifies another version.':'É necessário um JDK, não apenas um JRE. Prefira um JDK LTS suportado para ferramentas de QA, salvo exigência diferente do projeto.','Node.js includes npm. Prefer an LTS release for stable automation environments.':'Node.js inclui npm. Prefira uma versão LTS para ambientes de automação estáveis.','Node.js/npm are required. Android testing also needs Java JDK, Android SDK/platform-tools and a configured device/emulator. iOS automation requires macOS and Xcode.':'Node.js/npm são obrigatórios. Testes Android também exigem Java JDK, Android SDK/platform-tools e dispositivo/emulador configurado. Automação iOS exige macOS e Xcode.','Python and pip must be installed. Use a virtual environment to isolate project dependencies.':'Python e pip devem estar instalados. Use ambiente virtual para isolar as dependências do projeto.','Node.js LTS and npm are required.':'Node.js LTS e npm são obrigatórios.'}
  return mp.get(s,s)
 if lang=='es':
  mp={'No extra runtime is required.':'No se requiere un runtime adicional.','Node.js LTS and npm are required.':'Se requieren Node.js LTS y npm.','Python and pip must be installed. Use a virtual environment to isolate project dependencies.':'Python y pip deben estar instalados. Use un entorno virtual para aislar las dependencias del proyecto.'}
  return mp.get(s,s)
 return s


def command_explain(cmd,lang):
 c=cmd.lower().strip()
 msg={
 'version':{'pt':'Confirma que o executável está acessível e informa a versão. Se não houver resposta válida, corrija instalação/PATH antes de continuar.','en':'Confirms the executable is available and reports its version. If it fails, fix installation/PATH before continuing.','es':'Confirma que el ejecutable está disponible e informa su versión. Si falla, corrija instalación/PATH antes de continuar.'},
 'install':{'pt':'Instala o componente/dependência indicado. Aguarde a conclusão e confirme uma mensagem de sucesso.','en':'Installs the specified component/dependency. Wait for completion and confirm a success message.','es':'Instala el componente/dependencia indicado. Espere a que termine y confirme un mensaje de éxito.'},
 'list':{'pt':'Lista os componentes já instalados; use a saída para confirmar que o item esperado está presente.','en':'Lists already installed components; use the output to confirm the expected item is present.','es':'Lista los componentes ya instalados; use la salida para confirmar que el elemento esperado está presente.'},
 'venv':{'pt':'Cria um ambiente virtual isolado; ao final deve existir a pasta .venv.','en':'Creates an isolated virtual environment; a .venv directory should exist afterward.','es':'Crea un entorno virtual aislado; al finalizar debe existir la carpeta .venv.'},
 'activate':{'pt':'Ativa o ambiente virtual; normalmente o prompt passa a exibir (.venv).','en':'Activates the virtual environment; the prompt normally shows (.venv).','es':'Activa el entorno virtual; normalmente el prompt muestra (.venv).'},
 'run':{'pt':'Executa a validação funcional inicial. Leia a saída completa e confirme que não há falhas.','en':'Runs the initial functional validation. Read the complete output and confirm there are no failures.','es':'Ejecuta la validación funcional inicial. Lea toda la salida y confirme que no existen fallos.'},
 'generic':{'pt':'Execute no terminal indicado, leia toda a saída e resolva qualquer erro antes do próximo passo.','en':'Run it in the indicated terminal, read the complete output and resolve any error before the next step.','es':'Ejecútelo en el terminal indicado, lea toda la salida y resuelva cualquier error antes del siguiente paso.'}}
 if 'driver list' in c or c.startswith('npm list') or c.endswith('config --list'): typ='list'
 elif 'activate' in c or 'source .venv' in c: typ='activate'
 elif 'venv' in c: typ='venv'
 elif '--version' in c or ' -v' in c or c.endswith(' version'): typ='version'
 elif ' install ' in (' '+c+' ') or c.startswith('npm install') or c.startswith('pip install'): typ='install'
 elif any(x in c for x in [' run ',' test','hello-world','archetype:generate']): typ='run'
 else: typ='generic'
 return msg[typ][lang]

def header_footer(c,doc):
 c.saveState();w,h=A4;c.setFillColor(colors.HexColor('#0b3b6e'));c.setFont('Helvetica-Bold',10);c.drawString(42,h-30,'QA LAB BRASIL');c.setFont('Helvetica',7.5);c.setFillColor(colors.HexColor('#60758b'));c.drawString(42,h-41,'Quality Engineering');c.setStrokeColor(colors.HexColor('#cfe3f3'));c.line(42,h-48,w-42,h-48);c.setFont('Helvetica',7);c.drawRightString(w-42,24,f'QA Lab Brasil | {doc.page}');c.restoreState()

def action_text(x,lang,title):
 if lang=='en': return x
 # Commands remain unchanged. Narrative first-use actions are localized without leaking English.
 low=x.lower()
 iscmd=any(tok in low for tok in [' --',' -m ','npm ','npx ','python','java ','git ','docker ','kubectl ','terraform','mvn ','gradle','jmeter','k6 ','locust','allure ','adb ','code ','prometheus','\\scripts\\','source .venv','appium']) and not low.startswith(('open ','launch ','use ','create ','configure ','perform '))
 if iscmd: return x
 if lang=='pt':
  if x.startswith('Open http'): return 'Abra '+x.split('Open ',1)[1].split(' after ',1)[0]+' no navegador depois que o serviço estiver em execução.'
  if x.startswith('Launch '): return 'Abra '+title+' e conclua a validação inicial descrita neste manual.'
  return 'Execute a etapa de primeiro uso indicada para '+title+' e confirme visualmente que terminou sem erros.'
 if x.startswith('Open http'): return 'Abra '+x.split('Open ',1)[1].split(' after ',1)[0]+' en el navegador después de que el servicio esté en ejecución.'
 if x.startswith('Launch '): return 'Abra '+title+' y complete la validación inicial descrita en este manual.'
 return 'Realice la etapa de primer uso indicada para '+title+' y confirme visualmente que finalizó sin errores.'

def os_text(k,lang,field,title):
 if lang=='en': return P[k][field]
 idx={'win':0,'mac':1,'linux':2}[field]
 if k in OS_LOCAL: return OS_LOCAL[k][lang][idx]
 osn={'win':'Windows','mac':'macOS','linux':'Linux'}[field]
 return (f'Instale {title} pelo método oficial específico para {osn}, valide os pré-requisitos e execute os comandos desta seção antes de avançar.' if lang=='pt' else f'Instale {title} mediante el método oficial específico para {osn}, valide los prerrequisitos y ejecute los comandos de esta sección antes de continuar.')

def pre_text(k,lang,title):
 # Equal-depth localized prerequisite block; OS-specific details are immediately below.
 p=P[k]['pre']
 if lang=='en': return p
 deps=[]
 for token,labelpt,labeles in [('node','Node.js/npm','Node.js/npm'),('jdk','JDK/Java','JDK/Java'),('python','Python/pip','Python/pip'),('android','Android SDK/platform-tools','Android SDK/platform-tools'),('docker','Docker','Docker')]:
  if token in p.lower(): deps.append(labelpt if lang=='pt' else labeles)
 base=', '.join(dict.fromkeys(deps))
 if lang=='pt': return ('Confirme permissões de instalação e acesso à internet.' + (f' Pré-requisitos específicos: {base}.' if base else '') + ' Use somente versões suportadas pela documentação oficial da ferramenta.')
 return ('Confirme permisos de instalación y acceso a Internet.' + (f' Prerrequisitos específicos: {base}.' if base else '') + ' Use únicamente versiones compatibles según la documentación oficial de la herramienta.')

def expect_text(k,lang,title):
 if lang=='en': return P[k]['expect']
 # Keep result specific by describing the actual first-use command/action.
 first=P[k]['first'][0] if P[k]['first'] else ''
 if lang=='pt': return f'{title} deve concluir a validação sem erros. Na etapa de primeiro uso ({action_text(first,lang,title)}), confirme o comportamento esperado e ausência de falhas de instalação, PATH ou dependências.'
 return f'{title} debe completar la validación sin errores. En el primer uso ({action_text(first,lang,title)}), confirme el comportamiento esperado y la ausencia de fallos de instalación, PATH o dependencias.'

def is_command_item(x):
 low=x.lower().strip()
 return not low.startswith(('open ','launch ','use ','create ','configure ','perform ')) and (any(tok in low for tok in [' --',' -m ','npm ','npx ','python','java ','git ','docker ','kubectl ','terraform','mvn ','gradle','jmeter','k6 ','locust','allure ','adb ','code ','prometheus','appium','\\scripts\\','source .venv']) or ('\\' in x and ' ' not in x))

def add_steps(story, items, lang, title):
 for i,x in enumerate(items,1):
  story.append(Paragraph(f'<b>{i}.</b> {esc(action_text(x,lang,title))}',B))

def build(k,lang):
 d=D[k][lang]; meta=D[k].get('_meta',{}); p=P[k]; t=T[lang]; out=os.path.join(ROOT,f'pdf/{lang}/{k}-installation.pdf')
 doc=SimpleDocTemplate(out,pagesize=A4,leftMargin=42,rightMargin=42,topMargin=62,bottomMargin=42,title=f'{d["title"]} - {t["title"]}')
 story=[Paragraph(esc(d['title']),H1),Paragraph(esc(t['title']),H2),Paragraph(esc(t['aud']),SM),Spacer(1,5),Paragraph(esc(t['objective']),H2),Paragraph(esc(t['obj']),B),Paragraph(esc(t['before']),H2),Paragraph(esc(pre_text(k,lang,d['title'])),B)]
 urls=[]
 for fld in ('official','docs','download'):
  u=meta.get(fld)
  if u and u not in urls: urls.append(u)
 story += [Paragraph(esc(t['official']),H2)]
 for u in urls: story.append(Paragraph(f'<link href="{esc(u)}">{esc(u)}</link>',B))
 story += [Paragraph(esc(t['attention']),H2),Paragraph(esc(t['att']),WARN),Paragraph(esc(t['terminal']),H2),Paragraph(esc(t['terminal_text']),B)]
 for head,field in [(t['windows'],'win'),(t['mac'],'mac'),(t['linux'],'linux')]:
  story.append(Paragraph(esc(head),H2)); story.append(Paragraph(esc(os_text(k,lang,field,d['title'])),B))
  cmds=p['setup'] if field=='win' else p['unix']
  for cmd in cmds: story.append(Paragraph(esc(action_text(cmd,lang,d['title'])),CODE if is_command_item(cmd) else B))
 story.append(Paragraph(esc(t['verify']),H2)); add_steps(story,p['verify'],lang,d['title'])
 for cmd in p['verify']:
  if not cmd.lower().startswith(('open ','launch ','use ','create ','configure ')): story.append(Paragraph(esc(cmd),CODE))
 story.append(Paragraph(esc(t['commands']),H2))
 add_steps(story,p['setup'],lang,d['title'])
 for cmd in p['setup']:
  if len(cmd)<180:
   story.append(Paragraph(esc(action_text(cmd,lang,d['title'])),CODE if is_command_item(cmd) else B))
   if is_command_item(cmd): story.append(Paragraph(esc(command_explain(cmd,lang)),SM))
 # Novice-oriented environment and recovery guidance.
 envhead={'pt':'PATH, variáveis e novo terminal','en':'PATH, environment variables and a new terminal','es':'PATH, variables de entorno y nuevo terminal'}[lang]
 envtxt={'pt':'Quando o instalador adicionar um executável ao PATH ou você configurar uma variável como JAVA_HOME/ANDROID_HOME, feche o terminal antigo e abra um novo CMD/PowerShell. Depois repita o comando de versão. Se houver duas versões instaladas, use where <comando> no Windows ou which <comando> no macOS/Linux para descobrir qual executável está sendo usado. Não apague entradas de PATH sem saber a origem.','en':'When an installer adds an executable to PATH or you configure a variable such as JAVA_HOME/ANDROID_HOME, close the old terminal and open a new CMD/PowerShell. Then repeat the version command. If multiple versions are installed, use where <command> on Windows or which <command> on macOS/Linux to identify the executable being used. Do not remove PATH entries without understanding their origin.','es':'Cuando un instalador agregue un ejecutable a PATH o configure una variable como JAVA_HOME/ANDROID_HOME, cierre el terminal anterior y abra uno nuevo. Luego repita el comando de versión. Si existen varias versiones, use where <comando> en Windows o which <comando> en macOS/Linux para identificar el ejecutable utilizado. No elimine entradas de PATH sin conocer su origen.'}[lang]
 story.append(Paragraph(envhead,H2));story.append(Paragraph(esc(envtxt),B))
 folderhead={'pt':'Organize uma pasta de teste','en':'Create a safe test folder','es':'Organice una carpeta de prueba'}[lang]
 foldertxt={'pt':'Para os primeiros testes, use uma pasta simples e sem arquivos de produção, por exemplo C:\\Projetos\\qa-lab ou ~/qa-lab. Isso facilita identificar arquivos gerados, ambientes virtuais, logs e configurações.','en':'For the first tests, use a simple folder with no production files, for example C:\\Projects\\qa-lab or ~/qa-lab. This makes generated files, virtual environments, logs and configuration easier to identify.','es':'Para las primeras pruebas, utilice una carpeta simple y sin archivos de producción, por ejemplo C:\\Proyectos\\qa-lab o ~/qa-lab. Esto facilita identificar archivos generados, entornos virtuales, logs y configuraciones.'}[lang]
 story.append(Paragraph(folderhead,H2));story.append(Paragraph(esc(foldertxt),B))
 story.append(Paragraph(esc(t['first']),H2)); add_steps(story,p['first'],lang,d['title'])
 for cmd in p['first']:
  if len(cmd)<180 and not cmd.lower().startswith(('open ','launch ','use ','create ','configure ','perform ')): story.append(Paragraph(esc(cmd),CODE))
 story.append(Paragraph(esc(t['expected']),H2)); story.append(Paragraph(esc(expect_text(k,lang,d['title'])),CALLOUT))
 story.append(Paragraph(esc(t['trouble']),H2));
 troubles={
 'pt':[t['nexttxt'],'Comando não encontrado: confirme se o diretório de instalação está no PATH e abra um novo terminal.','Versão incorreta: verifique se outro runtime ou executável antigo aparece antes no PATH.','Permissão negada: use uma pasta de projeto gravável pelo usuário e siga a orientação oficial; não execute tudo como administrador/root sem necessidade.','Proxy/firewall corporativo: configure a ferramenta conforme a política de rede da organização, sem desativar controles de segurança.'],
 'en':[t['nexttxt'],'Command not found: confirm the installation directory is on PATH and open a new terminal.','Wrong version: check whether another older runtime or executable appears earlier on PATH.','Permission denied: use a user-writable project directory and follow the vendor permission guidance; do not blindly run everything as administrator/root.','Corporate proxy/firewall: configure the package manager/tool according to your organization network policy rather than disabling security controls.'],
 'es':[t['nexttxt'],'Comando no encontrado: confirme que el directorio de instalación está en PATH y abra un terminal nuevo.','Versión incorrecta: compruebe si otro runtime o ejecutable antiguo aparece antes en PATH.','Permiso denegado: use una carpeta de proyecto con permisos de escritura y siga la orientación oficial; no ejecute todo como administrador/root sin necesidad.','Proxy/firewall corporativo: configure la herramienta según la política de red de la organización, sin desactivar controles de seguridad.']
 }[lang]
 for x in troubles: story.append(Paragraph('• '+esc(x),B))
 story.append(Paragraph(esc(t['check']),H2))
 checks=[t['official'],t['windows']+' / '+t['mac']+' / '+t['linux'],t['verify'],t['first'],t['expected'],t['trouble']]
 for x in checks: story.append(Paragraph('☐ '+esc(x),B))
 story.append(Paragraph(esc(t['done']),CALLOUT))
 doc.build(story,onFirstPage=header_footer,onLaterPages=header_footer)

for k in keys:
 for lang in ('pt','en','es'): build(k,lang)
print('generated',len(keys)*3,'novice installation manuals')
